### PR TITLE
Don't error if deleting a non-existant pusher.

### LINKED ISSUE #5101: synapse.api.errors.StoreError: 404: No row found (pushers)
### Description

Errors in synapse log:
```
    2019-04-26 13:17:52,980 - synapse.push.httppusher - 144 - ERROR - httppush.process-34525- Exception processing notifs 
    Traceback (most recent call last): 
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/push/httppusher.py", line 142, in _process
        yield self._unsafe_process()
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/push/httppusher.py", line 178, in _unsafe_process
        self.clock.time_msec()
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/pusher.py", line 307, in update_pusher_last_stream_ordering_and_success
        desc="update_pusher_last_stream_ordering_and_success",
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/_base.py", line 393, in runInteraction
        *args, **kwargs
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/_base.py", line 442, in runWithConnection
        inner_func, *args, **kwargs
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/threadpool.py", line 250, in inContext
        result = inContext.theWork()
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
        inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
        return self.currentContext().callWithContext(ctx, func, *args, **kw)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
        return func(*args,**kw)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
        compat.reraise(excValue, excTraceback)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/compat.py", line 464, in reraise
        raise exception.with_traceback(traceback)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
        result = func(conn, *args, **kw)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/_base.py", line 438, in inner_func
        return func(conn, *args, **kwargs)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/_base.py", line 314, in _new_transaction
        r = func(txn, *args, **kwargs)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/_base.py", line 1031, in _simple_update_one_txn
        raise StoreError(404, "No row found (%s)" % (table,))
    synapse.api.errors.StoreError: 404: No row found (pushers)

```

### Version information

- **Homeserver**: 

If not matrix.org:

- **Version**: 
```
Server: nginx/1.10.3
ii  matrix-synapse                  0.34.0.1-0matrix2              all          transitional package
ii  matrix-synapse-py3              0.99.1.1+stretch1              amd64        Open federated Instant Messaging and VoIP server
ii  python-daemonize                2.3.1-0matrix1                 all          Library to enable your code run as a daemon process on Unix-
ii  python-frozendict               0.4-0matrix1                   all          An immutable dictionary
ii  python-phonenumbers             8.4.0~matrix~jessie1           all          Python port of Google libphonenumber
ii  python-pydenticon               0.2-0matrix1                   all          Library for generating identicons. Port of Sigil

```
- **Install method**: 

deb
- **Platform**: 

Debian 9.8

### PR DESCRIPTION
**Pull request by clokep**
I believe what is happening is that the request to delete a push is occurring more than once and only one of the requests can process successfully. Other requests end up with a `StoreError 404`. I don't see any reason why we need to enforce deleting exactly one pusher here.

Fixes #5101

Fixes https://sentry.matrix.org/sentry/synapse-matrixorg/issues/194918/?query=is%3Aunresolved

### CODE REVIEW

**Comment by richvdh** [comment]
fixes https://github.com/matrix-org/synapse/issues/5101 I guess

File: changelog.d/9121.bugfix [hunk 1]
```diff
@@ -0,0 +1 @@
+Do not throw spurious errors when deleting a non-existant pusher.
```
Comment (erikjohnston) [inline changelog.d/9121.bugfix:1]:
```suggestion
Fix spurious errors in logs when deleting a non-existant pusher.
```

**Review by erikjohnston — APPROVED** [review]
