### PR TITLE
Pin poetry.core in Docker images

### LINKED ISSUE #12854: Dependencies issue in recent Docker images
[CI](https://github.com/matrix-org/synapse/runs/6566243070?check_suite_focus=true#step:6:1866) complains about a missing on matrix-common and we've seen similar reports about Jinja:

```
Traceback (most recent call last):

  File "/start.py", line 11, in <module>

    import jinja2

ModuleNotFoundError: No module named 'jinja2'
```

### PR DESCRIPTION
**Pull request by erikjohnston**
I *think* this should fix the docker images. It's unclear as to why, though a beta `poetry.core` package was released yesterday, and we don't pin the version of *that* 

Fixes #12854

### CODE REVIEW

**Review by babolivier — APPROVED** [review]
Happy if CI passes

File: docker/Dockerfile [hunk 1]
```diff
@@ -45,17 +45,11 @@ RUN \
...
-#    https://github.com/python-poetry/poetry/pull/5156 and
-#    https://github.com/python-poetry/poetry/issues/5141 ;
-# without it, we generate a requirements.txt with incorrect environment markers,
-# which causes necessary packages to be omitted when we `pip install`.
 #
 # NB: In poetry 1.2 `poetry export` will be moved into a plugin; we'll need to also
 # pip install poetry-plugin-export (https://github.com/python-poetry/poetry-plugin-export).
 RUN --mount=type=cache,target=/root/.cache/pip \
-  pip install --user git+https://github.com/python-poetry/poetry.git@fb13b3a676f476177f7937ffa480ee5cff9a90a5
+  pip install --user "poetry==1.1.3"
```
Comment (babolivier) [inline docker/Dockerfile:52]: Actually:

```suggestion
  pip install --user "poetry==1.1.13"
```

Thanks @tulir for pointing it out

**Comment by richvdh** [comment]
better PR subject and description please. The current ones will make zero sense in a few months time :innocent:

**Comment by erikjohnston** [comment]
Have updated the linked issue

**Comment by erikjohnston** [comment]
Complement tests seem to be fixed :tada:

File: docker/Dockerfile [hunk 2]
```diff
@@ -43,8 +43,6 @@ RUN \
  apt-get update && apt-get install -y git \
     && rm -rf /var/lib/apt/lists/*
 
-# We install poetry in its own build stage to avoid its dependencies conflicting with
-# synapse's dependencies.
```
Comment (DMRobertson) [inline docker/Dockerfile:47]: I think this comment is still correct?

Comment (erikjohnston) [reply docker/Dockerfile:47]: woops

File: docker/Dockerfile [hunk 3]
```diff
@@ -55,7 +55,7 @@ RUN \
 # NB: In poetry 1.2 `poetry export` will be moved into a plugin; we'll need to also
 # pip install poetry-plugin-export (https://github.com/python-poetry/poetry-plugin-export).
 RUN --mount=type=cache,target=/root/.cache/pip \
-  pip install --user git+https://github.com/python-poetry/poetry.git@fb13b3a676f476177f7937ffa480ee5cff9a90a5
+  pip install --user "poetry-core==1.1.0a7" "git+https://github.com/python-poetry/poetry.git@fb13b3a676f476177f7937ffa480ee5cff9a90a5"
```
Comment (DMRobertson) [inline docker/Dockerfile:58]: I remember fighting with this a lot, though I can't exactly remember what this commit did for us. Probably a case of "latest master fixed it" and this was the commit at the time.

I also remember that after I updated some dependency specifications in signedjson that there were suddenly fewer bugs with the export. Given that the debian image doesn't use this commit, I wonder if it might be worth trying to use the same version that the docker image uses.

**Review by DMRobertson — COMMENTED** [review]
I'm a bit surprised this works---by default pip doesn't pull prerelease images from PyPI. Maybe it does if you install from a git repository.

Are the debian images also affected? We're using poetry 1.2.0b1 there.

https://github.com/matrix-org/synapse/blob/0ce2201932488e98cab8a7d81788e5bcf8f8dd5e/debian/build_virtualenv#L33-L46

**Comment by erikjohnston** [comment]
I don't think the Debian images are affected, as I think latest poetry is fine. I agree probably would be good to use a consistent version of poetry across Debian and Docker, but given this is currently breaking CI I am keen to do the bare minimum to fix this for now.

**Review by DMRobertson — APPROVED** [review]

**Comment by erikjohnston** [comment]
> Maybe it does if you install from a git repository.

Possibly because the git commit is versioned with a beta

File: changelog.d/12853.docker [hunk 4]
```diff
@@ -0,0 +1 @@
+Fix the docker file after a dependency update.
```
Comment (MadLittleMods) [inline changelog.d/12853.docker:1]: This changelog entry is not very descriptive and doesn't explain why we made the change (what was broken before).

For reference, these changes are spawning from some discussion in [#synapse-dev:matrix.org](https://matrix.to/#/!XaqDhxuTIlvldquJaV:matrix.org/$3yGRxuxblgIXMXapjUE4cTDEXTVqjduYTK7eDQc2Ufc?via=matrix.org&via=element.io&via=vector.modular.im) which discusses the `ModuleNotFoundError: No module named 'matrix_common'` errors popping up when [Complement is running in CI](https://github.com/matrix-org/synapse/runs/6566243070?check_suite_focus=true#step:6:1866).

As far as I can tell, the dependency was missing in CI because of this reason mentioned in the room discussion:

> hmm, the lockfile is changing all deps to from main to dev category :/
> Yeah, that seems to be the problem, as export ignores dev deps by default :/
>
> *-- [@erikjohnston](https://matrix.to/#/!XaqDhxuTIlvldquJaV:matrix.org/$56fcBKskPHkq5hCP4xt7MXAuC4JMRBJ5rEejdqjzT0M?via=matrix.org&via=element.io&via=vector.modular.im)*

As the issue description already mentions, the root cause might be because we didn't pin `poetry-core` before and it was pulling in a recent beta release which introduced the unexpected problem behavior.

---

This information should also be in the PR description. I'm not confident in my conclusion here to update it myself.

> better PR subject and description please. The current ones will make zero sense in a few months time 😇
>
> *-- @richvdh, https://github.com/matrix-org/synapse/pull/12853#issuecomment-1135660687*
