### PR TITLE
Fix a bug introduced in Synapse v1.0.0 whereby device list updates would not be sent to remote homeservers if there were too many to send at once.

### LINKED ISSUE #11727: Device list updates to be sent over federation will be skipped if there are too many at one time
`get_device_updates_by_remote` always returns the next stream position as the latest device stream token, even in cases where it is limited to a maximum number of rows to return.
The effect of this is that any device updates that don't fit within one `limit`-sized batch will be skipped.

Discovered whilst looking into #11719. Due to the nature of my fix to #11719, I'll likely fix them both at the same time.

### PR DESCRIPTION
**Pull request by reivilibre**
Fixes #11727: you can't resume reading the stream if there are more than `limit` entries because you get told to continue from the end of the stream, not the end of where you read up to.

Of note: #7010: stream_ids used to not be unique, but the ones produced in modern times are (since v1.13.0). Thanks Erik for saving me a lot of pain!

It appears to have been introduced in https://github.com/matrix-org/synapse/commit/2d1d7b7e6f2bec3b96b0d23993369ce46aad4f32, which has been there since the good ol' days of v1.0.0 :).

Required change for the fix to #11719, which is a release blocker.

### CODE REVIEW

File: changelog.d/11729.bugfix [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix a bug introduced in Synapse v1.0.0 whereby device list updates would not be sent to remote homeservers if there were too many to send at once.
```
Comment (babolivier) [inline changelog.d/11729.bugfix:1]:
```suggestion
Fix a bug introduced in Synapse v1.0.0 whereby some device list updates would not be sent to remote homeservers if there were too many to send at once.
```

**Review by babolivier — APPROVED** [review]

**Comment by DMRobertson** [comment]
Ahh, this is targeted at 1.50, which doesn't have the CI fix.
