### PR TITLE
Fix bug /sync returning 404

### LINKED ISSUE #12571: `/sync` returns 404 with "Could not find event" if  the last event in a room was rejected
`/sync` requests fail with logs like the following:

```
2022-04-27 19:52:55,224 - synapse.http.server - 95 - INFO - GET-2574276 - <XForwardedForRequest at 0x7fbc161945d8 method='GET' uri='/_matrix/client/r0/sync?filter=139&timeout=0&since=s2893808910_757284974_3577632_1332288051_1339908640_3205332_474955574_3498902419_212414' clientproto='HTTP/1.1' site='21126'> SynapseError: 404 - Could not find event $4KSidiqM831pDAWAg0CikeahLWUySLhqAHadbBKtucI
```

The event id in question is a rejected event.

Stacktrace for the exception:

```
  File "/home/synapse/src/synapse/handlers/sync.py", line 407, in current_sync_for_user
    sync_config, since_token, full_state
  File "/home/synapse/src/synapse/handlers/sync.py", line 1114, in generate_sync_result
    sync_result_builder, account_data_by_room
  File "/home/synapse/src/synapse/handlers/sync.py", line 1624, in _generate_sync_entry_for_rooms
    await concurrently_execute(handle_room_entries, room_entries, 10)
  File "/home/synapse/src/synapse/util/async_helpers.py", line 236, in concurrently_execute
    _concurrently_execute_inner, (value for value in itertools.islice(it, limit))
  File "/home/synapse/src/synapse/util/async_helpers.py", line 276, in yieldable_gather_results
    raise dfe.subFailure.value from None
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 1660, in _inlineCallbacks
    result = current_context.run(gen.send, result)
  File "/home/synapse/src/synapse/util/async_helpers.py", line 227, in _concurrently_execute_inner
    await maybe_awaitable(func(value))
  File "/home/synapse/src/synapse/handlers/sync.py", line 1619, in handle_room_entries
    always_include=sync_result_builder.full_state,
  File "/home/synapse/src/synapse/handlers/sync.py", line 2127, in _generate_room_entry
    full_state=full_state,
  File "/home/synapse/src/synapse/handlers/sync.py", line 956, in compute_state_delta
    room_id, stream_position=since_token, state_filter=state_filter
  File "/home/synapse/src/synapse/handlers/sync.py", line 669, in get_state_at
    end_token=stream_position.room_key,
  File "/home/synapse/src/synapse/storage/databases/main/stream.py", line 782, in get_last_event_in_room_before_stream_ordering
    event = await self.get_event(event_id, get_prev_content=True)
  File "/home/synapse/src/synapse/storage/databases/main/events_worker.py", line 402, in get_event
    raise NotFoundError("Could not find event %s" % (event_id,))
```

It looks like `get_last_event_in_room_before_stream_ordering` is returning that rejected event, and we're then trying to calculate the state at it.

Jaeger link for internal users: https://jaeger.proxy.matrix.org/trace/bc8f105a8857ad29?uiFind=562187d6a0f8c25a

### PR DESCRIPTION
**Pull request by erikjohnston**
I've based this on v1.59 branch, I think its worth sneaking this fix into v1.59.0

Fixes #12571

### CODE REVIEW

**Comment by erikjohnston** [comment]
I think the test failure is due to this not being up to date with develop?

**Comment by DMRobertson** [comment]
> I think the test failure is due to this not being up to date with develop?

It looks like we would need #12683. Do we want to include that in the release branch too?

File: changelog.d/12729.bugfix [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix uncommon bug where `/sync` would break for a user. Broke in v1.58.0.
```
Comment (DMRobertson) [inline changelog.d/12729.bugfix:1]:
```suggestion
Fix a bug introduced in Synapse 1.58.0 where `/sync` would fail if the more recent event in a room was rejected.
```

**Review by DMRobertson — APPROVED** [review]
Dunno if it's worth a test case?

File: synapse/storage/databases/main/stream.py [hunk 2]
```diff
@@ -743,14 +743,17 @@ async def get_room_event_before_stream_ordering(
...
-                " LIMIT 1"
-            )
+            sql = """
+                SELECT stream_ordering, topological_ordering, event_id
+                FROM events
+                LEFT JOIN rejections USING (event_id)
+                WHERE room_id = ?
+                    AND stream_ordering <= ?
+                    AND NOT outlier
+                    AND rejections.reason IS NULL
```
Comment (squahtx) [inline synapse/storage/databases/main/stream.py:753]: I'm having trouble understanding how #12319 broke things. The previous code did a `get_recent_events_for_room`, which looks like it doesn't check for rejection either?

**Comment by erikjohnston** [comment]
> > I think the test failure is due to this not being up to date with develop?
> 
> It looks like we would need #12683. Do we want to include that in the release branch too?

I'd rather not put more into this release if we can help it. I can live with complement failing that one test for now

File: synapse/storage/databases/main/stream.py (hunk 2 above)
Comment (erikjohnston) [reply synapse/storage/databases/main/stream.py:753]: Oh, hmm, you're right. The PR did make it worse though as the query actually doubles the specified limit (to take account of filtering), so before we'd have to have two rejected events next to each other to hit the bug

**Comment by DMRobertson** [comment]
Complement failure is expected, see above.
