### PR TITLE
Fix sample_config.yaml in regards track_puppeted_user_ips

### LINKED ISSUE #11741: sample doc in #11561 is malformatted
see https://github.com/matrix-org/synapse/pull/11561#pullrequestreview-851817482

### PR DESCRIPTION
**Pull request by jaywink**
Follow on from #11561 
Closes #11741

Signed-off-by: Jason Robinson <jasonr@matrix.org>

### CODE REVIEW

**Comment by DMRobertson** [comment]
LGTM. I'll fix up the EOL whitespace to make the linter happy.

**Review by DMRobertson — APPROVED** [review]

File: changelog.d/11749.doc [hunk 1]
```diff
@@ -0,0 +1 @@
+Update room spec url in config files.
```
Comment (jaywink) [inline changelog.d/11749.doc:1]: Wasn't aware fixes like this to previous PR's would require changelogs, sorry. However, the changelog here doesn't seem related? :thinking:

Comment (DMRobertson) [reply changelog.d/11749.doc:1]: No worries: the linter is merciless. It wants a changelog for every PR.

Looks like I got my PR numbers wrong, argh. Thanks for spotting!
