### PR TITLE
Fix /key/v2/server calls with URL-unsafe key IDs

### LINKED ISSUE #14488: synapse does not escape forward slashes in key IDs when making a federation `key/v2/server/...` request
https://github.com/matrix-org/synapse/blob/d8cc86eff484b6f570f55a5badb337080c6e4dcd/synapse/crypto/keyring.py#L857-L874

urllib.parse.quote doesn't escape slashes by default: because it expects to given an entire url path

ouchie

### PR DESCRIPTION
**Pull request by DMRobertson**
Fixes #14488.

I haven't yet done an audit of everywhere else we call urllib.parse.quote---suggest making that a separate task.

### CODE REVIEW

**Review by clokep — APPROVED** [review]

File: changelog.d/14490.misc [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix a bug introduced in Synapse 0.9 we would fail to fetch server keys whose IDs contain a forward slash.
```
Comment (clokep) [inline changelog.d/14490.misc:1]:
```suggestion
Fix a bug introduced in Synapse 0.9 where it would fail to fetch server keys whose IDs contain a forward slash.
```
