### PR TITLE
Fix typing replication not being handled on master

### LINKED ISSUE #7907: typing replication stream starts from stream_id 0 on reconnect
After the replication stream dropped, the replication handler streamed all 5 million typing updates ever, which took 10 minutes:
```
2020-07-20 09:27:10,630 - synapse.replication.tcp.handler - 593 - INFO -  - Lost replication connection; streams now disconnected: {'backfill', 'caches', 'typing', 'events'}
2020-07-20 09:27:13,624 - synapse.replication.tcp.handler - 471 - INFO - replication-POSITION-10159 - Handling 'POSITION typing typing-1 5018044'
2020-07-20 09:27:13,625 - synapse.replication.tcp.handler - 505 - INFO - replication-POSITION-10159 - Fetching replication rows for 'typing' between 0 and 5018044
```

### PR DESCRIPTION
**Pull request by erikjohnston**
Handling of incoming typing stream updates from replication was not
hooked up on master, effecting set ups where typing was handled on a
different worker.

This is really only a problem if the master process is also handling
sync requests, which is unlikely for those that are at the stage of
moving typing off.

The other observable effect is that if a worker restarts or a
replication connect drops then the typing worker will issue a
`POSITION typing`, triggering master process to try and stream *all*
typing updates from position 0.

Fixes #7907

### CODE REVIEW

File: changelog.d/7959.bugfix [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix typing notifications on master process when using another worker for typing stream.
```
Comment (clokep) [inline changelog.d/7959.bugfix:1]: This can probably be the same #7869 since it hasn't been released yet?

```suggestion
Add experimental support for moving typing off master.
```
