### PR TITLE
Fix error when selecting between thumbnails with the same quality

### LINKED ISSUE #10318: Traceback when fetching remote media
### Description

When I was watching the homeserver.log file I noticed the following lines going by.
```text
2021-07-05 22:56:01,678 - synapse.http.server - 93 - ERROR - GET-114720 - Failed handle request via 'ThumbnailResource': <XForwardedForRequest at 0x7f74e7313400 method='GET' uri='/_matrix/media/r0/thumbnail/matrix.org/dOhWUOiqfTEPQASnYCLKLINu?width=800&height=600&method=scale' clientproto='HTTP/1.1' site='8008'>
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/http/server.py", line 258, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/http/server.py", line 286, in _async_render
    callback_return = await raw_callback_return
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/rest/media/v1/thumbnail_resource.py", line 83, in _async_render_GET
    await self._respond_remote_thumbnail(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/rest/media/v1/thumbnail_resource.py", line 265, in _respond_remote_thumbnail
    await self._select_and_respond_with_thumbnail(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/rest/media/v1/thumbnail_resource.py", line 306, in _select_and_respond_with_thumbnail
    file_info = self._select_thumbnail(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/rest/media/v1/thumbnail_resource.py", line 481, in _select_thumbnail
    thumbnail_info = min(info_list)[-1]
TypeError: '<' not supported between instances of 'dict' and 'dict'
```
I couldn't find an open or closed issue regarding this error so I thought I'd open an issue for it.

### Steps to reproduce

I can reproduce it with curl
```
curl "https://matrix.moritzdietz.com/_matrix/media/r0/thumbnail/matrix.org/dOhWUOiqfTEPQASnYCLKLINu?width=800&height=600&method=scale"
```
which results in the error above.
I can fetch the media just fine via matrix.org:
```bash
curl -L "https://matrix-federation.matrix.org/_matrix/media/r0/thumbnail/matrix.org/dOhWUOiqfTEPQASnYCLKLINu?width=800&height=600&method=scale" -o somemedia.png
```

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: `matrix.moritzdietz.com`

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: `1.37.1`

- **Install method**: `package manager`
<!-- examples: package manager/git clone/pip  -->

- **Platform**: `Ubuntu 20.04 Server`
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->
I have `dynamic_thumbnails` set to false (as it's the default).

### PR DESCRIPTION
**Pull request by squahtx**
Fixes #10318 

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [x] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

### CODE REVIEW

File: changelog.d/10684.bugfix [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix error when a thumbnail is requested and there are multiple thumbnails with the same quality rating.
```
Comment (richvdh) [inline changelog.d/10684.bugfix:1]:
```suggestion
Fix long-standing issue which caused an error when a thumbnail is requested and there are multiple thumbnails with the same quality rating.
```

File: tests/rest/media/v1/test_media_storage.py [hunk 2]
```diff
@@ -473,6 +473,43 @@ def _test_thumbnail(self, method, expected_body, expected_found):
                 },
             )
 
+    @parameterized.expand([("crop", 16), ("crop", 64), ("scale", 16), ("scale", 64)])
+    def test_same_quality(self, method, desired_size):
+        """Test that choosing between thumbnails with the same quality rating succeeds.
+
+        We are not particular about which thumbnail is chosen."""
+        self.assertTrue(
```
Comment (richvdh) [inline tests/rest/media/v1/test_media_storage.py:481]: assertNotNone?

**Review by richvdh — APPROVED** [review]
looks good to me otherwise!
