### PR TITLE
Fix joining rooms you have been unbanned from

### LINKED ISSUE #1563: unbans do not propagate to federated servers (SYN-725)
Submitted by @&#8203;richvdh:sw1v.org
1. ban user on remote server 
2. re-invite user on remote server
3. user receives invite but their HS still thinks they are banned

(Imported from https://matrix.org/jira/browse/SYN-725)

----

Complement test blocked by this issue: https://github.com/matrix-org/complement/blob/3865b81da267f9c5e904e58b234c0a57a262ec04/tests/federation_room_ban_test.go?rgh-link-date=2016-07-13T19%3A37%3A37Z#L15

### PR DESCRIPTION
**Pull request by deepbluev7**
Since forever synapse did not allow you to join a room after you have been unbanned from it over federation. This was not actually because of the unban event not federating. Synapse simply used outdated state to validate the join transition. This skips the validation if we are not in the room and for that reason won't have the current room state.

Fixes #1563

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

### CODE REVIEW

**Comment by deepbluev7** [comment]
Corresponding complement test, maybe someone can remind me how the branch matching works, if I open a complement PR to unskip that test: https://github.com/matrix-org/complement/blob/3865b81da267f9c5e904e58b234c0a57a262ec04/tests/federation_room_ban_test.go?rgh-link-date=2016-07-13T19%3A37%3A37Z#L15

Also I hope this doesn't disable the wrong join validation, the logic of that function is really weird :)

**Comment by deepbluev7** [comment]
(The diff looks like a mess, but I just put a large block in an if block :D)

**Comment by deepbluev7** [comment]
Hm, the sytest seems to be failing, because there is no servername provided when trying to do the remote join and so it returns 400 instead of 403... :D

**Comment by deepbluev7** [comment]
Sytest fix needed for this: https://github.com/matrix-org/sytest/pull/1341

File: changelog.d/15323.bugfix [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix joining rooms you have been unbanned from over federation. Introduced before Synapse bugs were tracked on Github. Contributed by Nico.
```
Comment (reivilibre) [inline changelog.d/15323.bugfix:1]:
```suggestion
Fix a long-standing bug preventing users from joining rooms, that they had been unbanned from, over federation. Contributed by Nico.
```

as much as 'before bugs were on github' is a fun timescale, I guess we should just put 'long-standing' like we usually do :p

**Review by reivilibre — APPROVED** [review]

**Comment by reivilibre** [comment]
Thank you very much for the fix!!!

**Comment by reivilibre** [comment]
> maybe someone can remind me how the branch matching works

I think you should just need to match branch names, but it's probably broken for forks
