### PR TITLE
Fix PostgreSQL sometimes using table scans for `event_search`

### LINKED ISSUE #14402: Manually set `n_distinct` for `event_search.room_id` to avoid bad Postgres query plans
On matrix.org we discovered that every now and again `event_search` queries would take forever due to using the wrong query plan. This was due to Postgres underestimating the number of room IDs that existed. 

To fix this we should add a schema update with:

```sql
ALTER TABLE event_search ALTER COLUMN room_id SET (n_distinct = -0.01);
```

like we do for `state_groups_state.state_group` already.

### PR DESCRIPTION
**Pull request by squahtx**
PostgreSQL may underestimate the number of distinct `room_id`s in
`event_search`, which can cause it to use table scans for queries for
multiple rooms.

Fix this by setting `n_distinct` on the column.

Resolves #14402.

Signed-off-by: Sean Quah <seanq@matrix.org>

### CODE REVIEW

File: synapse/storage/schema/main/delta/73/11event_search_room_id_n_distinct.sql.postgres [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+-- distinct value). We don't need a particularly accurate number here, as a) we just
+-- want it to always use index scans and b) our estimate is going to be better than the
+-- one made by the statistics collector.
+
+ALTER TABLE event_search ALTER COLUMN room_id SET (n_distinct = -0.01);
+
+-- Ideally we'd do an `ANALYZE event_search (room_id)` here so that
+-- the above gets picked up immediately, but that can take a bit of time so we
+-- rely on the autovacuum eventually getting run and doing that in the
+-- background for us.
```
Comment (squahtx) [inline synapse/storage/schema/main/delta/73/11event_search_room_id_n_distinct.sql.postgres:33]: Comments shamelessly borrowed from #10359.

File: changelog.d/14409.bugfix [hunk 2]
```diff
@@ -0,0 +1 @@
+Fix PostgreSQL sometimes using table scans for queries against `event_search` table, taking a long time and a large amount of IO.
```
Comment (DMRobertson) [inline changelog.d/14409.bugfix:1]: `against` -> `against the`?

**Review by DMRobertson — APPROVED** [review]

File: changelog.d/14409.bugfix (hunk 2 above)
Comment (squahtx) [reply changelog.d/14409.bugfix]: oops, fixed.

**Comment by squahtx** [comment]
Thanks for the fast review!
