### PR TITLE
fix #3445 - do not use itervalues() on SortedDict()

### LINKED ISSUE #3445: Unhandled error in deferred: SortedDict.itervalues() is not implemented
This popped up in the log for t2bot.io. Unknown cause and unknown impact. Synapse 0.31.2
```
Traceback (most recent call last):
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/federation/send_queue.py", line 109, in _clear_queue
    self._clear_queue_before_pos(position_to_delete)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/federation/send_queue.py", line 122, in _clear_queue_before_pos
    for uids in itervalues(self.presence_changed)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/six.py", line 602, in itervalues
    return d.itervalues(**kw)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/sortedcontainers/sorteddict.py", line 370, in method
    raise AttributeError(message)
AttributeError: SortedDict.itervalues() is not implemented. Use SortedDict.values() instead.
```

### PR DESCRIPTION
**Pull request by krombel**
itervalues(d) calls d.itervalues() [PY2] and d.values() [PY3]
but SortedDict only implements d.values()

Signed-Off-by: Matthias Kesler <krombel@krombel.de>

### CODE REVIEW

File: changelog.d/3445.bugfix [hunk 1]
```diff
@@ -0,0 +1 @@
+do not use six.itervalues() on SortedDict()
```
Comment (erikjohnston) [inline changelog.d/3445.bugfix]: The changelog is broadly aimed at server admins, so could this be something more like "Fix bug in sending presence over federation" or something?

**Comment by erikjohnston** [comment]
@matrixbot ok to test
