### PR TITLE
Fix remove_stale_pushers job on SQLite.

### LINKED ISSUE #10824: Error on background update 'remove_stale_pushers'
### Description

Error on background update 'remove_stale_pushers' after upgrading synapse from 1.28.0 to 1.42.0.

I just upgraded my home server from 1.28.0 to 1.42.0 (I use the docker image), and I get the same error looping about every second in my log:
```
synapse    | 2021-09-15 06:15:16,111 - synapse.storage.background_updates - 230 - INFO - background_updates-0 - Starting update batch on background update 'remove_stale_pushers'
synapse    | 2021-09-15 06:15:16,124 - synapse.storage.background_updates - 117 - ERROR - background_updates-0 - Error doing update
synapse    | Traceback (most recent call last):
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/background_updates.py", line 113, in run_background_updates
synapse    |     result = await self.do_next_background_update(
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/background_updates.py", line 224, in do_next_background_update
synapse    |     await self._do_background_update(desired_duration_ms)
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/background_updates.py", line 261, in _do_background_update
synapse    |     items_updated = await update_handler(progress, batch_size)
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/databases/main/pusher.py", line 387, in _remove_stale_pushers
synapse    |     number_deleted = await self.db_pool.runInteraction(
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 686, in runInteraction
synapse    |     result = await self.runWithConnection(
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 791, in runWithConnection
synapse    |     return await make_deferred_yieldable(
synapse    |   File "/usr/local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 238, in inContext
synapse    |     result = inContext.theWork()  # type: ignore[attr-defined]
synapse    |   File "/usr/local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 254, in <lambda>
synapse    |     inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
synapse    |   File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 118, in callWithContext
synapse    |     return self.currentContext().callWithContext(ctx, func, *args, **kw)
synapse    |   File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 83, in callWithContext
synapse    |     return func(*args, **kw)
synapse    |   File "/usr/local/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 293, in _runWithConnection
synapse    |     compat.reraise(excValue, excTraceback)
synapse    |   File "/usr/local/lib/python3.8/site-packages/twisted/python/deprecate.py", line 298, in deprecatedFunction
synapse    |     return function(*args, **kwargs)
synapse    |   File "/usr/local/lib/python3.8/site-packages/twisted/python/compat.py", line 404, in reraise
synapse    |     raise exception.with_traceback(traceback)
synapse    |   File "/usr/local/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 284, in _runWithConnection
synapse    |     result = func(conn, *args, **kw)
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 786, in inner_func
synapse    |     return func(db_conn, *args, **kwargs)
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 554, in new_transaction
synapse    |     r = func(cursor, *args, **kwargs)
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/databases/main/pusher.py", line 372, in _delete_pushers
synapse    |     self.db_pool.simple_delete_many_txn(
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 1902, in simple_delete_many_txn
synapse    |     txn.execute(sql, values)
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 298, in execute
synapse    |     self._do_execute(self.txn.execute, sql, *args)
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 331, in _do_execute
synapse    |     return func(sql, *args)
synapse    | sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 8, and there are 0 supplied.
synapse    | 2021-09-15 06:15:17,129 - synapse.storage.background_updates - 230 - INFO - background_updates-0 - Starting update batch on background update 'remove_stale_pushers'
synapse    | 2021-09-15 06:15:17,141 - synapse.storage.background_updates - 117 - ERROR - background_updates-0 - Error doing update
synapse    | Traceback (most recent call last):
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/background_updates.py", line 113, in run_background_updates
synapse    |     result = await self.do_next_background_update(
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/background_updates.py", line 224, in do_next_background_update
synapse    |     await self._do_background_update(desired_duration_ms)
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/background_updates.py", line 261, in _do_background_update
synapse    |     items_updated = await update_handler(progress, batch_size)
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/databases/main/pusher.py", line 387, in _remove_stale_pushers
synapse    |     number_deleted = await self.db_pool.runInteraction(
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 686, in runInteraction
synapse    |     result = await self.runWithConnection(
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 791, in runWithConnection
synapse    |     return await make_deferred_yieldable(
synapse    |   File "/usr/local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 238, in inContext
synapse    |     result = inContext.theWork()  # type: ignore[attr-defined]
synapse    |   File "/usr/local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 254, in <lambda>
synapse    |     inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
synapse    |   File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 118, in callWithContext
synapse    |     return self.currentContext().callWithContext(ctx, func, *args, **kw)
synapse    |   File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 83, in callWithContext
synapse    |     return func(*args, **kw)
synapse    |   File "/usr/local/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 293, in _runWithConnection
synapse    |     compat.reraise(excValue, excTraceback)
synapse    |   File "/usr/local/lib/python3.8/site-packages/twisted/python/deprecate.py", line 298, in deprecatedFunction
synapse    |     return function(*args, **kwargs)
synapse    |   File "/usr/local/lib/python3.8/site-packages/twisted/python/compat.py", line 404, in reraise
synapse    |     raise exception.with_traceback(traceback)
synapse    |   File "/usr/local/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 284, in _runWithConnection
synapse    |     result = func(conn, *args, **kw)
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 786, in inner_func
synapse    |     return func(db_conn, *args, **kwargs)
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 554, in new_transaction
synapse    |     r = func(cursor, *args, **kwargs)
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/databases/main/pusher.py", line 372, in _delete_pushers
synapse    |     self.db_pool.simple_delete_many_txn(
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 1902, in simple_delete_many_txn
synapse    |     txn.execute(sql, values)
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 298, in execute
synapse    |     self._do_execute(self.txn.execute, sql, *args)
synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 331, in _do_execute
synapse    |     return func(sql, *args)
synapse    | sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 8, and there are 0 supplied.
```

I use an SQLite database.

Everything else seems fine (I'm able to connect to and use the server with Element).

FWIW I ran the same migration (from docker image 1.28.0 to 1.42.0) on a test server before, without any problem. The test server had an almost empty database though, so it's probably related...

I tried rolling back to 1.41.0 but I get the same looping error, so I stayed on 1.42.0.
I tried restarting the container but the error stayed.

### Version information

- **Homeserver**: My own private home server...

- **Version**: {
  "server_version": "1.42.0",
  "python_version": "3.8.12"
}

SQLite database.

- **Platform**: docker container on Ubuntu 18.04.5 LTS

----

Is there a way to fix my database? Or does this isssue require a synapse patch?

EDIT: for now, I just removed the failing task (`delete from background_updates where update_name = "remove_stale_pushers";`)...
I tried to investigate a bit, but didn't get very far. I suspect the problem was introduced in https://github.com/matrix-org/synapse/pull/9536.

### PR DESCRIPTION
**Pull request by reivilibre**
We iterate twice over the same Iterable, expecting it to be the
same size each time.
This is not valid; instead we should demand a Collection.

Fixes #10824.

Intended to be commit-by-commit friendly, if you like.

### CODE REVIEW

File: changelog.d/10843.bugfix [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix a bug causing the `remove_stale_pushers` background job to repeatedly fail and log errors, when SQLite is in use and Synapse is upgraded from version 1.28 or older.
```
Comment (squahtx) [inline changelog.d/10843.bugfix:1]: nit: the comma here doesn't sound right

**Review by squahtx — APPROVED** [review]
LGTM, one comment about the changelog

File: changelog.d/10843.bugfix (hunk 1 above)
Comment (reivilibre) [reply changelog.d/10843.bugfix:1]: you're right; was trying to make it more digestible but didn't work.

**Review by squahtx — APPROVED** [review]
