### PR TITLE
Ensure emails are canonicalized before fetching associated user.

### LINKED ISSUE #11458: Emails are not canonicalised on /_matrix/client/*/pushers/set
### Description

Emails sent to `/pushers/set` are not canonicalised, while they probably should.

### Steps to reproduce

- choose an email with an uppercase letter in it, e.g. `FooBar@example.com`
- set that email to a user via the admin API. The email will end up normalized in the DB
- try to set an email pusher with the same email. It should work but doesn't and returns with an `Email not found` error

### Version information

- **Homeserver**: other
- **Version**: 1.47.0
- **Install method**: Docker/Kubernetes
- **Platform**: N/A

---

Here, the `pushkey` should definitely be canonicalised for emails:

https://github.com/matrix-org/synapse/blob/8c7a531e277f98ac6b7981b9738649f3a70feb94/synapse/push/pusherpool.py#L115-L118

using `canonicalise_email`:

https://github.com/matrix-org/synapse/blob/8c7a531e277f98ac6b7981b9738649f3a70feb94/synapse/util/threepids.py#L66-L69

### PR DESCRIPTION
**Pull request by clokep**
Updates two callers of `get_user_id_by_threepid` to canonicalize the email argument. I audited other callers and ensured that they were fine (by calling `canonicalise_email` or `validate_email`).

Fixes #11458

### CODE REVIEW

File: changelog.d/11547.bugfix [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix a bug introduced in Synapse 1.17.0 where a pusher created for an email with capital letters would fail to be created.
```
Comment (clokep) [inline changelog.d/11547.bugfix:1]: #7021 added the canonical email stuff (I think) which was in Synapse 1.17.0, I'm not 100% sure what the behavior was before that though.

**Review by squahtx — APPROVED** [review]
lgtm!
