### PR TITLE
Fix failures in Debian packaging

### LINKED ISSUE #9073: Debian build fails due missing dh-systemd package on Bullseye
As per https://bugs.debian.org/822670, the `dh-systemd` package has been merged with the main `debhelper` package since version `9.20160709`

For some time, a transitional `dh-systemd` package existed which simply depended on `debhelper`. However, this was removed from bullseye.

The fix should be as simple as depending on `debhelper (>= 9.20160709)`, which available on all supported Debian releases and all supported Ubuntu releases *except* for xenial.

### LINKED ISSUE #9076: Debian builds fail with ascii encoding error on older distros
The Debian builds for debian:stretch, ubuntu:xenial, and ubuntu:bionic fail along these lines:

(Errors taken from an ubuntu:bionic container)

```
[ERROR]
Traceback (most recent call last):
  File "/synapse/build/venv/lib/python3.6/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/synapse/build/venv/lib/python3.6/site-packages/twisted/logger/_legacy.py", line 93, in __call__
    self.legacyObserver(event)
  File "/synapse/build/venv/lib/python3.6/site-packages/twisted/python/log.py", line 562, in emit
    util.untilConcludes(self.write, timeStr + " " + msgStr)
  File "/synapse/build/venv/lib/python3.6/site-packages/twisted/python/util.py", line 815, in untilConcludes
    return f(*a, **kw)
builtins.UnicodeEncodeError: 'ascii' codec can't encode characters in position 771-772: ordinal not in range(128)

tests.handlers.test_oidc.OidcHandlerTestCase.test_map_userinfo_to_invalid_localpart
```

```
[ERROR]
Traceback (most recent call last):
  File "/synapse/build/venv/lib/python3.6/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/synapse/build/venv/lib/python3.6/site-packages/twisted/logger/_legacy.py", line 93, in __call__
    self.legacyObserver(event)
  File "/synapse/build/venv/lib/python3.6/site-packages/twisted/python/log.py", line 562, in emit
    util.untilConcludes(self.write, timeStr + " " + msgStr)
  File "/synapse/build/venv/lib/python3.6/site-packages/twisted/python/util.py", line 815, in untilConcludes
    return f(*a, **kw)
builtins.UnicodeEncodeError: 'ascii' codec can't encode characters in position 803-804: ordinal not in range(128)

tests.handlers.test_saml.SamlHandlerTestCase.test_map_saml_response_to_invalid_localpart
```

Will investigate further in the morning.

### PR DESCRIPTION
**Pull request by callahad**
Debian package builds were failing for two reasons:

1. Python versions prior to 3.7 throw exceptions when attempting to print Unicode characters under a "C" locale.

2. We depended on `dh-systemd` which no longer exists in Debian Bullseye, but is necessary in Ubuntu Xenial.

Fixing the first issue is as easy as setting `LANG="C.UTF-8"` in the build environment. (See https://bugs.python.org/issue19846)

Fixing the second issue requires attempting to install `dh-systemd`, but ignoring failures when it does not exist.

Specifically, the `dh-systemd` package was merged with the main `debhelper` package as of debhelper (>= 9.20160709)` and a transitional package was left in its place.

That transitional package was removed in Debian Bullseye after being present in both Stretch and Buster. Thus, on the Debian side, just removing the dependency on `dh-systemd` would be sufficient.

However, Ubuntu Xenial has an old `debhelper` version, and thus actually needs `dh-systemd`. So we still try to install it on all distros, but ignore when that fails.

Once we drop support for Xenial (March 2021?) we can completely remove anything referencing `dh-systemd`.

Fixes #9073 
Fixes #9076

### CODE REVIEW

**Comment by callahad** [comment]
Cancelled CI since we don't test the Debian build scripts in CI.

Currently building all debs locally to ensure things work. Stretch completed successfully, and I expect no further failures.

File: debian/control [hunk 1]
```diff
@@ -3,9 +3,9 @@ Section: contrib/python
 Priority: extra
 Maintainer: Synapse Packaging team <packages@matrix.org>
 # keep this list in sync with the build dependencies in docker/Dockerfile-dhvirtualenv.
+# TODO: Remove the dependency on dh-systemd after dropping support for Ubuntu xenial
 Build-Depends:
- debhelper (>= 9),
- dh-systemd,
+ debhelper (>= 9.20160709) | dh-systemd,
```
Comment (callahad) [inline debian/control:8]: `dh-systemd` depends on `debhelper`, so if the newer `debhelper` is unavailable, we'll fall back to `dh-systemd` which will then itself pull in the older debhelper.

Nevertheless, we will only need to do this on Ubuntu xenial *without* xenial-backports, which should be exceptionally rare.

File: docker/Dockerfile-dhvirtualenv [hunk 2]
```diff
@@ -70,7 +74,10 @@ RUN apt-get update -qq -o Acquire::Languages=none \
         python3-venv \
         sqlite3 \
         libpq-dev \
-        xmlsec1
+        xmlsec1 \
+    && ( env DEBIAN_FRONTEND=noninteractive apt-get install \
+         -yqq --no-install-recommends -o Dpkg::Options::=--force-unsafe-io \
+         dh-systemd || true )
```
Comment (callahad) [inline docker/Dockerfile-dhvirtualenv:80]: Per GitHub comment above, this basically says "try to install dh-systemd, but it's OK if it fails or doesn't exist."

dh-systemd exists as a dummy transitional package on all releases except Ubuntu xenial (sans backports), where we actually do need it. So we need to try to install it. However, the transitional package was removed in Debian Bullseye, so we have to gracefully continue even if the package does not exist.

...all this goes away when we drop Xenial support in ~2 months.

File: debian/control (hunk 1 above)
Comment (richvdh) [reply debian/control:8]: > Nevertheless, we will only need to do this on Ubuntu xenial without xenial-backports, which should be exceptionally rare.

well, this is run in the build environment, which is a docker image we control. I don't think it has backports enabled, but either way, it's either 0% or 100% of occasions we run the build...

File: changelog.d/9079.misc [hunk 3]
```diff
@@ -0,0 +1 @@
+Fix failures when building Debian packages
```
Comment (richvdh) [inline changelog.d/9079.misc:1]: This probably belongs in the debian changelog, not here.

**Review by richvdh — CHANGES_REQUESTED** [review]
thanks for poking at this. can you add some context to the PR about what broke and why, and how this fixes it?

File: debian/control (hunk 1 above)
Comment (richvdh) [reply debian/control:8]: > dh-systemd depends on debhelper, so if the newer debhelper is unavailable, we'll fall back to dh-systemd which will then itself pull in the older debhelper.

could you stick this comment in the file so that it doesn't get lost in the PR?

**Comment by callahad** [comment]
> thanks for poking at this. can you add some context to the PR about what broke and why, and how this fixes it?

Ah, yeah, that's in each commit message. Edited the initial comment to copy those over.

File: docker/Dockerfile-dhvirtualenv [hunk 4]
```diff
@@ -50,17 +50,21 @@ FROM ${distro}
 ARG distro=""
 ENV distro ${distro}
 
+# Python < 3.7 assumes LANG="C" means ASCII-only and throws on printing unicode
+# http://bugs.python.org/issue19846
+ENV LANG C.UTF-8
```
Comment (richvdh) [inline docker/Dockerfile-dhvirtualenv:55]: this is the Dockerfile used to build the build environment, rather than the Dockerfile used to build the synapse debs. Are you sure this is the right place?

Comment (callahad) [reply docker/Dockerfile-dhvirtualenv:55]: I believe you're mistaken; this is a multi-stage Dockerfile which first sets up the build environment and then builds the debs in a separate stage. This ENV stanza is within the stage that actually does the building.

Comment (richvdh) [reply docker/Dockerfile-dhvirtualenv:55]: oops. sorry.

File: debian/control (hunk 1 above)
Comment (callahad) [reply debian/control:8]: > this is run in the build environment, which is a docker image we control. I don't think it has backports enabled, but either way, it's either 0% or 100% of occasions we run the build...

It does have backports enabled but we should specify these dependencies as robustly as possible in case someone needed to rebuild the package locally (e.g., `apt-get build-dep`, `apt-get source`, etc.)

> could you stick this comment

Done

File: changelog.d/9079.misc (hunk 3 above)
Comment (callahad) [reply changelog.d/9079.misc]: Done

File: debian/changelog [hunk 5]
```diff
@@ -1,3 +1,10 @@
+matrix-synapse-py3 (1.24.0+nmu1) UNRELEASED; urgency=medium
+
+  * Update dependencies to account for the removal of the transitional
```
Comment (richvdh) [inline debian/changelog:3]: ... And fix the tests on 3.5/3.6?

Comment (richvdh) [reply debian/changelog:3]: I guess that's not really a major user-facing change.

**Review by richvdh — APPROVED** [review]

File: debian/changelog (hunk 5 above)
Comment (callahad) [reply debian/changelog:3]: Yeah. And it's really only _our_ Docker-based build environments that broke, since you have to have both an older Python *and* `LANG=C` which should be very rare.

For example, our CI uses the "official" Docker images for Python, which set `LANG=C.UTF-8`, and any developer machine is likely to have a "real" locale set.
