### PR TITLE
Refuse to start if DB has an unsafe locale

### LINKED ISSUE #12055: Abort startup if unsafe DB locale
### Description

From https://github.com/matrix-org/synapse/issues/10718 :

> > Perhaps instead of a warning that should be made to abort startup unless a new setting `corrup_my_db_silently_on_libc_update: true` is set.
> 
> We're fine going with this approach to at least help people avoid silent corruption... details tbd.

We should probably also add the commands needed to drop the broken data from a DB to https://matrix-org.github.io/synapse/latest/postgres.html#fixing-incorrect-collate-or-ctype and also add:

> We should also probably link to information on how Glibc collation changes can break PostgreSQL. E.g., https://wiki.postgresql.org/wiki/Locale_data_changes

### Steps to reproduce

- have DB use wrong locale
- update libc with locale change
- notice corrupt DB

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? 
- **Homeserver**:

If not matrix.org:
-->
<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: seen e.g. on 1.41.0, but bug exists before and after

- **Install method**: any
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Linux glibc
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

### PR DESCRIPTION
**Pull request by H-Shay**
Currently Synapse will refuse to start new deployments if they have an unsafe DB locale. This PR extends that behavior to existing deployments, unless the user sets the new config flag `allow_unsafe_locale` added in this PR. Fixes #12055.

### CODE REVIEW

File: changelog.d/12262.misc [hunk 1]
```diff
@@ -0,0 +1 @@
+Refuse to start if DB has non-c locale, unless config flag `allow_unsafe_db_locale` is set to true.
```
Comment (reivilibre) [inline changelog.d/12262.misc:1]:
```suggestion
Refuse to start if DB has non-`C` locale, unless config flag `allow_unsafe_db_locale` is set to true.
```

C is a proper noun... probably. And I suppose it's a constant.

File: synapse/config/database.py [hunk 2]
```diff
@@ -37,6 +37,12 @@
 # 'txn_limit' gives the maximum number of transactions to run per connection
 # before reconnecting. Defaults to 0, which means no limit.
 #
+# 'allow_unsafe_locale' is an option specific to postgres. Under the default behavior, Synapse will refuse to
+# start if the postgres db is set to a non-c locale. You can override this behavior (which is *not* recommended)
```
Comment (reivilibre) [inline synapse/config/database.py:41]:
```suggestion
# 'allow_unsafe_locale' is an option specific to Postgres. Under the default behavior, Synapse will refuse to
# start if the postgres db is set to a non-C locale. You can override this behavior (which is *not* recommended)
```

File: synapse/storage/engines/postgres.py [hunk 3]
```diff
@@ -72,33 +81,31 @@ def check_database(self, db_conn, allow_outdated_version: bool = False):
...
-            )
-            collation, ctype = txn.fetchone()
+            collation, ctype = self.get_db_locale(txn)
             if collation != "C":
-                logger.warning(
-                    "Database has incorrect collation of %r. Should be 'C'\n"
-                    "See docs/postgres.md for more information.",
-                    collation,
-                )
+                if not allow_unsafe_locale:
```
Comment (reivilibre) [inline synapse/storage/engines/postgres.py:86]: Would be tempted to flatten this nested if to `if collation != "C" and not allow_unsafe_locale:`.
Actually, scratch that, I'd be tempted to still log a warning when the config flag is enabled, just thinking that it's good to have the log file reveal when a 'tainted configuration' is being used.

File: tests/storage/test_unsafe_locale.py [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+from unittest.mock import patch
+
+from synapse.storage.database import make_conn
+from synapse.storage.engines._base import IncorrectDatabaseSetup
+from synapse.storage.engines.postgres import PostgresEngine
+
+from tests.unittest import HomeserverTestCase
+
+
+class UnsafeLocaleTest(HomeserverTestCase):
```
Comment (reivilibre) [inline tests/storage/test_unsafe_locale.py:23]: You will probably need to add the import for this, but looking at other tests with `rg` (since I vaguely remembered seeing it), this is how we usually skip Postgres-specific tests.
That way, they're neither marked as a failure nor a success on SQLite, which I guess is pedantically more correct.
Would imagine it avoids the overhead of setting up a test homeserver + database just to not do anything :-).

```suggestion
class UnsafeLocaleTest(HomeserverTestCase):
    if not USE_POSTGRES_FOR_TESTS:
        skip = "Requires Postgres"

```

File: tests/storage/test_unsafe_locale.py [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+    @patch("synapse.storage.engines.postgres.PostgresEngine.get_db_locale")
+    def test_unsafe_locale(self, mock_db_locale):
+        mock_db_locale.return_value = ("B", "B")
```
Comment (reivilibre) [inline tests/storage/test_unsafe_locale.py:26]: ROFL at `B`...... Not sure I've ever seen *that* locale before :D. (no problem with leaving it; it's 'not C', just not a 'not C' I was expecting)

File: tests/storage/test_unsafe_locale.py [hunk 6]
```diff
@@ -0,0 +1,38 @@
...
+        database = self.hs.get_datastores().databases[0]
+
+        # Only run this on postgres databases
+        if isinstance(database.engine, PostgresEngine):
```
Comment (reivilibre) [inline tests/storage/test_unsafe_locale.py:30]: If we skip the test on Postgres we don't need to worry about obscuring the test code with this guard (and get to avoid boomeranging it).
In other situations, I've been told enough times (since I always forget in my own code), this could have been an early return to prevent the boomeranging also.

File: tests/storage/test_unsafe_locale.py [hunk 7]
```diff
@@ -0,0 +1,38 @@
...
+from synapse.storage.database import make_conn
+from synapse.storage.engines._base import IncorrectDatabaseSetup
+from synapse.storage.engines.postgres import PostgresEngine
+
+from tests.unittest import HomeserverTestCase
+
+
+class UnsafeLocaleTest(HomeserverTestCase):
+    @patch("synapse.storage.engines.postgres.PostgresEngine.get_db_locale")
+    def test_unsafe_locale(self, mock_db_locale):
```
Comment (reivilibre) [inline tests/storage/test_unsafe_locale.py:25]:
```suggestion
    def test_unsafe_locale(self, mock_db_locale) -> None:
```
Just so we can claim this file is type-checked :innocent: :-) (occasionally tests can be good places that exercise the type annotations a bit, providing valid type errors for mistakes in the actual code. Not sure it'd buy much here, but why not)

Don't know what the type of the Mock is, would be tempted to put it in but also suppose it stands very little chance of mattering.

File: tests/storage/test_unsafe_locale.py [hunk 8]
```diff
@@ -0,0 +1,38 @@
...
+        # Only run this on postgres databases
+        if isinstance(database.engine, PostgresEngine):
+            db_conn = make_conn(
+                database._database_config, database.engine, "test_unsafe"
+            )
+            with self.assertRaises(IncorrectDatabaseSetup):
+                database.engine.check_database(db_conn)
+            with self.assertRaises(IncorrectDatabaseSetup):
+                database.engine.check_new_database(db_conn)
+            db_conn.close()
```
Comment (reivilibre) [inline tests/storage/test_unsafe_locale.py:38]: I would be tempted to add another test: one that runs `get_db_locale` *without* mocking it, checking that:

- the query works
- `"C", "C"` is being used in the tests

**Review by reivilibre — CHANGES_REQUESTED** [review]
Looking good!

File: tests/storage/test_unsafe_locale.py (hunk 5 above)
Comment (H-Shay) [reply tests/storage/test_unsafe_locale.py:26]: I figured it didn't matter and was a little cheeky joke but if you want me to change it to POSIX or whatever I am happy to do so.

**Review by reivilibre — APPROVED** [review]
Perfect! Thanks :)
