### PR TITLE
remove `retry_on_integrity_error` wrapper for persist_events

### LINKED ISSUE #7845: A room lost all its forward extremities, leading to "no create event in auth events"
this actually goes back to March; sadly this is the first time I've had a chance to write it up in a github issue.

Somehow a room (on the `mozilla.org` instance) ended up with no `event_forward_extremities` in the database at all, despite still having a number of local members.

The room was manually "fixed" by inserting a new row into `event_forward_extremities` and restarting synapse.

The only thing that looks odd is this entry in the postgres error log:

```
2020-03-04 15:14:33 UTC:172.20.37.63(58809):8e71e000-3607-11ea-8fb7-3d4a5344b740-live@8e71e000-3607-11ea-8fb7-3d4a5344b740-live:[14889]:ERROR: duplicate key value violates unique constraint "events_pkey"
2020-03-04 15:14:33 UTC:172.20.37.63(58809):8e71e000-3607-11ea-8fb7-3d4a5344b740-live@8e71e000-3607-11ea-8fb7-3d4a5344b740-live:[14889]:DETAIL: Key (stream_ordering)=(1691477) already exists.
2020-03-04 15:14:33 UTC:172.20.37.63(58809):8e71e000-3607-11ea-8fb7-3d4a5344b740-live@8e71e000-3607-11ea-8fb7-3d4a5344b740-live:[14889]:STATEMENT: INSERT INTO events (contains_url, depth, event_id, origin_server_ts, outlier, processed, received_ts, room_id, sender, stream_ordering, topological_ordering, type) VALUES(false, 5557, '$iVFN6H4LReXpOG_N0ygHoatqCO61LmyzNj5B9D6x-8M', 1583334868334, false, true, 1583334873818, '!<room>:mozilla.org', '@<sender>:mozilla.org', 1691477, 5557, 'm.room.message')
```

### PR DESCRIPTION
**Pull request by richvdh**
As far as I can tell from the sentry logs, the only time this has actually done anything in the last two years is when we had two master workers running at once, and even then, it made a bit of a mess of it (see https://github.com/matrix-org/synapse/issues/7845#issuecomment-658238739).

Generally I feel like this code is doing more harm than good.

Fixes #7845.

### CODE REVIEW

File: changelog.d/7848.misc [hunk 1]
```diff
@@ -0,0 +1 @@
+Remove redundant `retry_on_integrity_error` wrapper for event persistence code.
```
Comment (clokep) [inline changelog.d/7848.misc:1]: What makes this redundant? Is essentially the same thing done right now anyway?

Comment (richvdh) [reply changelog.d/7848.misc:1]: well, see the PR description.

Comment (clokep) [reply changelog.d/7848.misc:1]: So less redundant, and more not useful. OK.
