### PR TITLE
Populate the room version from state events

### LINKED ISSUE #7065: Initial /sync is returning 404 due to "unknown room" when processing an event.
My account is currently unable to initial /sync and is broken with:

```
$ grep GET-17237 initial_synchrotron4.log
2020-03-11 00:13:02,176 - synapse.storage.data_stores.main.events_worker - 592 - WARNING - GET-17237 - Room !YkSMpYmmunCikXWFkB:matrix.org for event $3AJgBnxl5BLJs3Sp0L3GWojCeItDi98uVpmuqWH-vJc is unknown
2020-03-11 00:13:02,177 - synapse.http.server - 81 - INFO - GET-17237 - <XForwardedForRequest at 0x7fb07b58ad68 method='GET' uri='/_matrix/client/r0/sync?filter=139&timeout=0' clientproto='HTTP/1.1' site=8108> SynapseError: 404 - Could not find event $3AJgBnxl5BLJs3Sp0L3GWojCeItDi98uVpmuqWH-vJc
2020-03-11 00:13:02,178 - synapse.access.http.8108 - 302 - INFO - GET-17237 - 92.234.32.44 - 8108 - {@matthew:matrix.org} Processed request: 3.956sec/0.000sec (2.098sec, 0.621sec) (0.203sec/1.574sec/2) 101B 404 "GET /_matrix/client/r0/sync?filter=139&timeout=0 HTTP/1.1" "Riot/0.11.0 (iPhone; iOS 13.3.1; Scale/3.00)" [1 dbevts]
```

The `$...-vJc` event is an invite event for my user to a room I hadn't yet accepted.

This circumstantially looks related to the new redaction stuff in #6875 - perhaps in conjunction with stuck invite bugs, or failing to set room_version on unaccepted invites, or something else...

### PR DESCRIPTION
**Pull request by babolivier**
Fixes #7065 

This is basically the same as https://github.com/matrix-org/synapse/pull/6847 except it tries to populate events from `state_events` rather than `current_state_events`, since this table might have been cleared from the state of some rooms too early, leaving them with a `NULL` room version.

### CODE REVIEW

File: synapse/storage/data_stores/main/schema/delta/57/rooms_version_column_3.sql.postgres [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+-- synchronous instead of running it in a background update, which fixed this issue.
+-- However, all of the instances of Synapse installed or updated in the meantime got
+-- their rooms table corrupted with NULL room_versions.
+
+-- This query fishes out the room versions from the create event using the state_events
+-- table instead of the current_state_events one, as the former still have all of the
+-- create events.
+
+UPDATE rooms SET room_version=(
+    SELECT COALESCE(json::json->'content'->>'room_version','1')
```
Comment (richvdh) [inline synapse/storage/data_stores/main/schema/delta/57/rooms_version_column_3.sql.postgres]: a comment for my future self:

for rooms where we don't have the create event, this `select` will return zero rows, which will mean the update will set `room_version = NULL`. That should only happen for out-of-band invites, which are covered by https://github.com/matrix-org/synapse/pull/6874/files/9cbd27ba61e17106564389142ed11c73ed9eafb5#diff-a155dd33efb484b1f8324c754c6ee55cR596.

File: changelog.d/7070.bugfix [hunk 2]
```diff
@@ -0,0 +1 @@
+Fix a bug causing `/sync` returning with 404 errors about missing events and unknown rooms.
```
Comment (richvdh) [inline changelog.d/7070.bugfix]:
```suggestion
Repair a data-corruption issue which was introduced in Synapse 1.10, and fixed in Synapse 1.11, and which could cause `/sync` to return with 404 errors about missing events and unknown rooms.
```
