### PR TITLE
Don't return `end` from `/messages` if there are no more events

### LINKED ISSUE #12102: `/messages` endpoint returns `end` token identical to `from` token
### Description

Goal is to fetch messages in a room backwards.

### Steps to reproduce

- My client first does a `/sync` to get the latest `next_batch` token
- I'm then using that token to pass it into the [messages endpoint](https://spec.matrix.org/v1.2/client-server-api/#get_matrixclientv3roomsroomidmessages) as `{ from: $next_batch, direction: "b", .. }`.
- The response from the server has an `end` field that's the same as the `next_batch` token that was used in the initial request, additionally to all room messages.
 
So it seems there's an issue with synapse not leaving the `end` token empty if it reaches the end of the timeline.

For reference, here's the raw response from synapse, where `start` and `end` are identical.

> matrix_sdk::http_client: Got response: Response { status: 200, version: HTTP/1.1, headers: {"transfer-encoding": "chunked", "server": "Synapse/1.53.0", "date": "Mon, 28 Feb 2022 14:45:37 GMT", "content-type": "application/json", "cache-control": "no-cache, no-store, must-revalidate", "access-control-allow-origin": "*", "access-control-allow-methods": "GET, HEAD, POST, PUT, DELETE, OPTIONS", "access-control-allow-headers": "X-Requested-With, Content-Type, Authorization, Date"}, body: b"{\"chunk\":[],\"start\":\"t1-915_1917_28_2_75_1_1_77_1\",\"end\":\"t1-915_1917_28_2_75_1_1_77_1\"}" }

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: Local dev instance

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.53.0

- **Install method**: docker hub
<!-- examples: package manager/git clone/pip  -->

- **Platform**: x86 64bit, docker container
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

### PR DESCRIPTION
**Pull request by Vetchu**
Fixes #12102.

Judging by this [comment](https://github.com/matrix-org/matrix-spec-proposals/issues/2251#issuecomment-932821615) and the [spec](https://spec.matrix.org/v1.2/client-server-api/#get_matrixclientv3roomsroomidmessages) this should fix the issue.

I'm not sure if end should be null if this was the last chunk of information but was non empty, but I do not know if it is possible to check if there are no more events in `next_token`.

Signed-off-by: Jacek Kuśnierz <kusnierz@protonmail.com>

### CODE REVIEW

**Comment by richvdh** [comment]
@Vetchu thank you for your contribution! Please could you add a sign-off, per https://matrix-org.github.io/synapse/develop/development/contributing_guide.html#sign-off?

File: changelog.d/12903.bugfix [hunk 1]
```diff
@@ -0,0 +1 @@
+Do not return end attribute when there are no more events.
```
Comment (richvdh) [inline changelog.d/12903.bugfix:1]:
```suggestion
Fix a long-standing bug which caused the `/messages` endpoint to return an incorrect `end` attribute when there were no more events. Contributed by @Vetchu.
```

File: synapse/handlers/pagination.py [hunk 2]
```diff
@@ -527,7 +527,6 @@ async def get_messages(
             return {
                 "chunk": [],
                 "start": await from_token.to_string(self.store),
-                "end": await next_token.to_string(self.store),
```
Comment (richvdh) [inline synapse/handlers/pagination.py:530]: I think for this to work correctly, we need to move this block further up (above the call to `event_filter.filter`.

The problem is that we hit this block if there are no *visible* events between the two tokens, but that might just be because the `event_filter` has filtered them all out. If we paginate further, we might find more events.

**Review by richvdh — CHANGES_REQUESTED** [review]

File: synapse/handlers/pagination.py (hunk 2 above)
Comment (Vetchu) [reply synapse/handlers/pagination.py:530]: Hmmm, that looks correct, I'll push another commit to fix that

File: synapse/handlers/pagination.py [hunk 3]
```diff
@@ -515,14 +515,23 @@ async def get_messages(
 
             next_token = from_token.copy_and_replace(StreamKeyType.ROOM, next_key)
 
-        if events:
-            if event_filter:
-                events = await event_filter.filter(events)
+        # if no events are returned from pagination
+        # do not return end - there's no need for further queries
```
Comment (richvdh) [inline synapse/handlers/pagination.py:519]:
```suggestion
        # if no events are returned from pagination, that implies
        # we have reached the end of the available events.
        # In that case we do not return end, to tell the client
        # there is no need for further queries
```

**Review by richvdh — APPROVED** [review]
looks great - thanks again!
