### PR TITLE
Install cryptography build dependencies in requirements image.

### LINKED ISSUE #13371: Docker image build fails on 32 bit Raspberry Pi
### Description

When trying to build a docker image on a 32 bit raspbian environment, the build fails because it cannot find a proper rust compiler for building the cryptography package. Note that this happens in the initial "poetry" stage, not the second one where the relevent dependencies are in fact installed using `apt`.

The command used was 
```
DOCKER_BUILDKIT=1 docker build --pull --build-arg PYTHON_VERSION=3.9 -f docker/Dockerfile -t synapse:v1.63.1 -t synapse:latest .
```
and the output scrolled of of my screen unfortunately.

### Steps to reproduce

- checkout git
- try to run a build: `DOCKER_BUILDKIT=1 docker build --pull --build-arg PYTHON_VERSION=3.9 -f docker/Dockerfile -t synapse:v1.63.1 -t synapse:latest .`

### Homeserver

n/a

### Synapse Version

1.63.1

### Installation Method

Other (please mention below)

### Platform

Raspi 4, raspbian 32 bits, has recent docker versions

### Relevant log output

```shell
scrolled of the screen unfortunately
```

### Anything else that would be useful to know?

PR incoming

### PR DESCRIPTION
**Pull request by jap**
This is needed because poetry depends on cryptography. Without this,
building fails when building on an architecture where an upstream
cryptography wheel is not available - for example, on an
armv7 (raspberry pi 4 not in 64 bits mode).

This fixes #13371 
Signed-off-by: Jasper Spaans <j@jasper.es>

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

### CODE REVIEW

File: changelog.d/13372.misc [hunk 1]
```diff
@@ -0,0 +1 @@
+Make docker images build on armv7 by installing cryptography dependencies in the "requirements" stage. Contributed by Jasper Spaans.
```
Comment (babolivier) [inline changelog.d/13372.misc:1]: As per https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog, changes to the Docker image should use the `.docker` extension.

**Review by babolivier — CHANGES_REQUESTED** [review]
lgtm apart from this, thanks for contributing!

File: changelog.d/13372.misc (hunk 1 above)
Comment (jap) [reply changelog.d/13372.misc:1]: Ok - note that I did put it in misc because it changes only an intermediate image, not the deliverable. Will update.

**Review by reivilibre — APPROVED** [review]
Thanks!
