### PR TITLE
Return NOT_JSON if decode fails and defer set_timeline_upper_limit ca…

### LINKED ISSUE #13661: "Invalid filter json" error message should use an appropriate error code
```json
{
  "errcode": "M_UNKNOWN",
  "error": "Invalid filter JSON"
}
```

From https://github.com/matrix-org/synapse/blob/a6895dd576f96d7fd086fb4128d48ac8a3f098c5/synapse/rest/client/sync.py#L145-L154

We should return `M_NOT_JSON` if the decode fails.

We should probably also defer the `set_timeline_upper_limit` call until `            self.filtering.check_valid_filter(filter_object)` has passed?

### PR DESCRIPTION
**Pull request by renegaderyu**
…ll until after check_valid_filter. Fixes #13661.

### Pull Request Checklist

* [X] Pull request is based on the develop branch
* [X] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [X] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [X] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

### CODE REVIEW

File: changelog.d/14262.misc [hunk 1]
```diff
@@ -0,0 +1 @@
+Return M_NOT_JSON rather than M_UNKNOWN when decode fails.
```
Comment (DMRobertson) [inline changelog.d/14262.misc:1]:
```suggestion
Provide a specific error code when a `/sync` request provides a filter which doesn't represent a JSON object.
```

**Review by DMRobertson — APPROVED** [review]
Thanks!
