### PR TITLE
Include extra dependency groups 'systemd' and 'cache_memory' in debian packages

### LINKED ISSUE #12631: Synapse not starting anymore after update to 1.58.0: ModuleNotFoundError: No module named 'systemd'
### Description
With a logging configuration that logs to systemd's journal, Synapse 1.58.0 doesn't restart anymore, because of
```
May 04 08:10:16 chat matrix-synapse[188389]: Traceback (most recent call last):
May 04 08:10:16 chat matrix-synapse[188389]:   File "/usr/lib/python3.9/logging/config.py", line 385, in resolve
May 04 08:10:16 chat matrix-synapse[188389]:     found = self.importer(used)
May 04 08:10:16 chat matrix-synapse[188389]: ModuleNotFoundError: No module named 'systemd'
May 04 08:10:16 chat matrix-synapse[188389]: The above exception was the direct cause of the following exception:
May 04 08:10:16 chat matrix-synapse[188389]: Traceback (most recent call last):
May 04 08:10:16 chat matrix-synapse[188389]:   File "/usr/lib/python3.9/logging/config.py", line 564, in configure
May 04 08:10:16 chat matrix-synapse[188389]:     handler = self.configure_handler(handlers[name])
May 04 08:10:16 chat matrix-synapse[188389]:   File "/usr/lib/python3.9/logging/config.py", line 722, in configure_handler
May 04 08:10:16 chat matrix-synapse[188389]:     klass = self.resolve(cname)
May 04 08:10:16 chat matrix-synapse[188389]:   File "/usr/lib/python3.9/logging/config.py", line 398, in resolve
May 04 08:10:16 chat matrix-synapse[188389]:     raise v
May 04 08:10:16 chat matrix-synapse[188389]:   File "/usr/lib/python3.9/logging/config.py", line 385, in resolve
May 04 08:10:16 chat matrix-synapse[188389]:     found = self.importer(used)
May 04 08:10:16 chat matrix-synapse[188389]: ValueError: Cannot resolve 'systemd.journal.JournalHandler': No module named 'systemd'
May 04 08:10:16 chat matrix-synapse[188389]: The above exception was the direct cause of the following exception:
May 04 08:10:16 chat matrix-synapse[188389]: Traceback (most recent call last):
May 04 08:10:16 chat matrix-synapse[188389]:   File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
May 04 08:10:16 chat matrix-synapse[188389]:     return _run_code(code, main_globals, None,
May 04 08:10:16 chat matrix-synapse[188389]:   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
May 04 08:10:16 chat matrix-synapse[188389]:     exec(code, run_globals)
May 04 08:10:16 chat matrix-synapse[188389]:   File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/app/homeserver.py", line 460, in <module>
May 04 08:10:16 chat matrix-synapse[188389]:     main()
May 04 08:10:16 chat matrix-synapse[188389]:   File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/app/homeserver.py", line 450, in main
May 04 08:10:16 chat matrix-synapse[188389]:     hs = setup(sys.argv[1:])
May 04 08:10:16 chat matrix-synapse[188389]:   File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/app/homeserver.py", line 377, in setup
May 04 08:10:16 chat matrix-synapse[188389]:     synapse.config.logger.setup_logging(hs, config, use_worker_options=False)
```
as long as this logging configuration is in place (which worked fine before):
```
version: 1

formatters:
  precise:
    format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'

handlers:
  journal:
    class: systemd.journal.JournalHandler
    formatter: precise
    level: INFO

loggers:
  synapse.storage.SQL:
    # beware: increasing this to DEBUG will make synapse log sensitive
    # information such as access tokens.
    handlers: [journal]
    level: INFO

  twisted:
    handlers: [journal]

root:
  handlers: [journal]
  level: INFO

disable_existing_loggers: true
```
If I comment out usage of this file in my homeserver.yaml, it works again. Guess this is due to the new Python packaging...

### Steps to reproduce
- Update to 1.58.0 using Debian package
- Restart the server with above logging config in place

### Version information
- **Version**: 1.58.0
- **Install method**: Debian package
- **Platform**: Debian Bullseye

### PR DESCRIPTION
**Pull request by anoadragon453**
Fixes #12631.

The `systemd` and `cache_memory` extra package groups contain python dependencies that are necessary for using all available options of the base distribution of Synapse in debian packages.

`systemd` provides the `systemd-python` package which is required for logging to the systemd journal, whereas `cache_memory` provides the `pympler` package, which is required for the `caches.track_memory_usage` homeserver config option.

These dependencies were available before the poetry changeover, where [they seem to have gone missing](https://github.com/matrix-org/synapse/issues/12631#issuecomment-1118418265). This PR adds these extras groups back.

Merging to the `release-v1.58` branch with the intention of including this in a v1.58.1 release.

---

I'm not sure if we also need to add the `cache_memory` extras group to the following line?

https://github.com/matrix-org/synapse/blob/0d8d59542abb99412f6b578350e765aa050df4c0/debian/build_virtualenv#L62

### CODE REVIEW

File: changelog.d/12640.misc [hunk 1]
```diff
@@ -0,0 +1 @@
+Re-include python dependencies from the `systemd` and `cache_memory` extras package groups in the Debian packages, after they were accidentally removed.
```
Comment (richvdh) [inline changelog.d/12640.misc:1]: as the lint check says - this needs to go in `debian/changelog`, not here.

File: debian/build_virtualenv [hunk 2]
```diff
@@ -37,7 +37,12 @@ python3 -m venv "$TEMP_VENV"
 source "$TEMP_VENV/bin/activate"
 pip install -U pip
 pip install poetry==1.2.0b1
-poetry export --extras all --extras test -o exported_requirements.txt
+poetry export \
+    --extras all \
+    --extras test \
+    --extras systemd \
+    --extras cache_memory \
```
Comment (richvdh) [inline debian/build_virtualenv:44]: I can't help but wonder if this is the right fix, or if we should go back to having `all` include, well, all the extras. (Or, most of them.)

(this used to be included via [this code](https://matrix.org/blog/2019/11/09/avoiding-unwelcome-visitors-on-private-matrix-servers) and [this code](https://github.com/matrix-org/synapse/blob/v1.56.0/setup.py#L88-L91)).

Comment (anoadragon453) [reply debian/build_virtualenv:44]: That is a good point. As it stands, the docker images also don't look to include `pympler`: https://github.com/matrix-org/synapse/blob/e5a76ec00b443c6e15ac8de2838a5c60a47a67ec/docker/Dockerfile#L64.

Comment (anoadragon453) [reply debian/build_virtualenv:44]: I'm assuming that dependencies for an experimental config option (`cache.track_memory_usage`) are in fact something that we'd like to include in Debian and Docker images, as they would allow people using those distribution methods to actually test the option.

In that case, including them in `all` sounds sensible.

Comment (richvdh) [reply debian/build_virtualenv:44]: sgtm

File: debian/changelog [hunk 3]
```diff
@@ -1,3 +1,9 @@
+matrix-synapse-py3 (1.58.0+nmu1) UNRELEASED; urgency=medium
+
+  * Re-include python dependencies from the `systemd` and `cache_memory` extras package groups.
```
Comment (richvdh) [inline debian/changelog:3]:
```suggestion
  * Include python dependencies from the `systemd` and `cache_memory` extras package groups, which
    were incorrectly omitted from the 1.58.0 package.
```

or something. "re-include" is really not a word :).

File: debian/build_virtualenv (hunk 2 above)
Comment (DMRobertson) [reply debian/build_virtualenv:44]: > I can't help but wonder if this is the right fix, or if we should go back to having `all` include, well, all the extras. (Or, most of them.)
> 
> (this used to be included via [this code](https://github.com/matrix-org/synapse/blob/v1.56.0/synapse/python_dependencies.py?rgh-link-date=2022-05-05T11%3A21%3A21Z#L121-L127) and [this code](https://github.com/matrix-org/synapse/blob/v1.56.0/setup.py?rgh-link-date=2022-05-05T11%3A21%3A21Z#L88-L91)).

By my reading, the first link explicitly excludes `systemd` from `all`. I can't remember why I didn't include pympler; maybe just an oversight.

**Review by richvdh — CHANGES_REQUESTED** [review]
lgtm othet than the changelog

**Review by richvdh — APPROVED** [review]
