### PR TITLE
Don't remember `enabled` of deleted push rules and properly return 404 for missing push rules in `.../actions` and `.../enabled`

### LINKED ISSUE #1475: adding push rule, disabling it, deleting it then adding new rule means the new rule starts off disabled. (SYN-596)
(Imported from https://matrix.org/jira/browse/SYN-596)

(Reported by @dbkr)

### LINKED ISSUE #1531: Enabling/disabling a unknown default push rule should 404. (SYN-676)
```
PUT /_matrix/client/r0/pushrules/global/override/.not.a.default.rule/enabled

{"enabled":true}
```

The above request should fail with a 404.

(Imported from https://matrix.org/jira/browse/SYN-676)

(Reported by @NegativeMjark)

### PR DESCRIPTION
**Pull request by reivilibre**
Fixes #1475. Fixes #1531. Requires [MSC2663](https://github.com/matrix-org/matrix-doc/pull/2663).

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [x] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

### CODE REVIEW

**Comment by reivilibre** [comment]
Going to open for review even though it depends on MSC2663

File: changelog.d/7796.bugfix [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix inconsistent handling of nonexistant push rules' and no longer latently track the 'enabled' bit of removed push rules.
```
Comment (richvdh) [inline changelog.d/7796.bugfix:1]:
```suggestion
Fix inconsistent handling of non-existent push rules, and stop tracking the `enabled` state of removed push rules.
```

File: synapse/storage/data_stores/main/push_rule.py [hunk 2]
```diff
@@ -13,7 +13,6 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-
```
Comment (richvdh) [inline synapse/storage/data_stores/main/push_rule.py:16]: this isn't an improvement, honestly, but not a big deal.

File: synapse/rest/client/v1/push_rule.py [hunk 3]
```diff
@@ -162,6 +161,21 @@ def notify_user(self, user_id):
...
+            # 404 in the case of an unknown request so check it corresponds to
+            # a known attribute first.
+            raise UnrecognizedRequestError()
+
+        namespaced_rule_id = _namespaced_rule_id_from_spec(spec)
+        rule_id = spec["rule_id"]
+        is_default_rule = rule_id.startswith(".")
+        if is_default_rule:
+            if namespaced_rule_id not in BASE_RULE_IDS:
+                raise SynapseError(
```
Comment (richvdh) [inline synapse/rest/client/v1/push_rule.py:175]: `NotFoundError` is a thing.

File: synapse/rest/client/v1/push_rule.py [hunk 4]
```diff
@@ -162,6 +161,21 @@ def notify_user(self, user_id):
...
+                    404, "Unknown rule %r" % (namespaced_rule_id,), Codes.NOT_FOUND
```
Comment (richvdh) [inline synapse/rest/client/v1/push_rule.py:176]: probably prefer %s here?
```suggestion
                    404, "Unknown rule %s" % (namespaced_rule_id,), Codes.NOT_FOUND
```

File: synapse/storage/data_stores/main/push_rule.py [hunk 5]
```diff
@@ -656,12 +662,31 @@ def set_push_rule_enabled(self, user_id, rule_id, enabled):
...
+
+        if not is_default_rule:
+            try:
+                # first check it exists
+                self.db.simple_select_one_onecol_txn(
+                    txn, "push_rules", {"user_name": user_id, "rule_id": rule_id}, "id"
+                )
+            except StoreError as serr:
+                if serr.code == 404:
+                    raise StoreError(404, "Push rule does not exist.", Codes.NOT_FOUND)
```
Comment (richvdh) [inline synapse/storage/data_stores/main/push_rule.py:688]: this feels a bit redundant?

(if the objective is to make the error nicer, it might be better to do this at a higher level?)

File: synapse/storage/data_stores/main/push_rule.py [hunk 6]
```diff
@@ -645,7 +651,7 @@ def delete_push_rule_txn(txn, stream_id, event_stream_ordering):
             )
 
     @defer.inlineCallbacks
-    def set_push_rule_enabled(self, user_id, rule_id, enabled):
+    def set_push_rule_enabled(self, user_id, rule_id, enabled, is_default_rule):
```
Comment (richvdh) [inline synapse/storage/data_stores/main/push_rule.py:654]: it'd be nice to add some type annotations and doc strings while you're passing.

File: synapse/storage/data_stores/main/push_rule.py [hunk 7]
```diff
@@ -656,12 +662,31 @@ def set_push_rule_enabled(self, user_id, rule_id, enabled):
...
+        rule_id,
+        enabled,
+        is_default_rule,
     ):
         new_id = self._push_rules_enable_id_gen.get_next()
+
+        if not is_default_rule:
+            try:
+                # first check it exists
+                self.db.simple_select_one_onecol_txn(
```
Comment (richvdh) [inline synapse/storage/data_stores/main/push_rule.py:683]: I'm not sure about this, but you might need to `SELECT FOR UPDATE` to ensure that, if an update races with a delete, we don't end up with a dangling `enabled` row.

possibly best to discuss in #synapse-dev

File: synapse/storage/data_stores/main/push_rule.py [hunk 8]
```diff
@@ -702,12 +727,20 @@ def set_push_rule_actions_txn(txn, stream_id, event_stream_ordering):
...
+                        {"user_name": user_id, "rule_id": rule_id},
+                        {"actions": actions_json},
+                    )
+                except SynapseError as serr:
+                    if serr.code == 404:
+                        raise SynapseError(
+                            404, "Push rule does not exist", Codes.NOT_FOUND
+                        )
+                    else:
+                        raise serr
```
Comment (richvdh) [inline synapse/storage/data_stores/main/push_rule.py:743]: we want to allow the exception to propagate with its original stacktrace, rather than raising it as a new exception.

```suggestion
                        raise
```

File: synapse/storage/data_stores/main/push_rule.py [hunk 9]
```diff
@@ -702,12 +727,20 @@ def set_push_rule_actions_txn(txn, stream_id, event_stream_ordering):
...
+                try:
+                    self.db.simple_update_one_txn(
+                        txn,
+                        "push_rules",
+                        {"user_name": user_id, "rule_id": rule_id},
+                        {"actions": actions_json},
+                    )
+                except SynapseError as serr:
+                    if serr.code == 404:
+                        raise SynapseError(
```
Comment (richvdh) [inline synapse/storage/data_stores/main/push_rule.py:739]: suggest `NotFoundError` here

File: synapse/storage/data_stores/main/push_rule.py [hunk 10]
```diff
@@ -702,12 +727,20 @@ def set_push_rule_actions_txn(txn, stream_id, event_stream_ordering):
...
-                    {"actions": actions_json},
-                )
+                try:
+                    self.db.simple_update_one_txn(
+                        txn,
+                        "push_rules",
+                        {"user_name": user_id, "rule_id": rule_id},
+                        {"actions": actions_json},
+                    )
+                except SynapseError as serr:
```
Comment (richvdh) [inline synapse/storage/data_stores/main/push_rule.py:737]: probably tighten this to `StoreError`

File: synapse/storage/data_stores/main/schema/delta/59/pushrules_enabled_delete_obsolete.sql [hunk 11]
```diff
@@ -0,0 +1,32 @@
+/* Copyright 2020 The Matrix.org Foundation C.I.C.
```
Comment (richvdh) [inline synapse/storage/data_stores/main/schema/delta/59/pushrules_enabled_delete_obsolete.sql:1]: I think this file is in the wrong directory; should be /58/ ?

also can it have a number please.

File: synapse/storage/data_stores/main/schema/delta/59/pushrules_enabled_delete_obsolete.sql [hunk 12]
```diff
@@ -0,0 +1,32 @@
...
+ *
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+/**
+  Delete stuck 'enabled' bits that correspond to deleted push rules.
```
Comment (richvdh) [inline synapse/storage/data_stores/main/schema/delta/59/pushrules_enabled_delete_obsolete.sql:17]:
```suggestion
  Delete stuck 'enabled' bits that correspond to deleted or non-existent push rules.
```

File: synapse/storage/data_stores/main/schema/delta/59/pushrules_enabled_delete_obsolete.sql [hunk 13]
```diff
@@ -0,0 +1,32 @@
...
+  We ignore rules that are server-default rules because they are not defined
+  in the `push_rules` table.
+**/
+
+DELETE FROM push_rules_enable pre WHERE
+  pre.rule_id NOT LIKE 'global/override/.%'
```
Comment (richvdh) [inline synapse/storage/data_stores/main/schema/delta/59/pushrules_enabled_delete_obsolete.sql:23]: meh, `NOT LIKE 'global/%/.m.rule.%'` should do here

File: tests/rest/client/v1/test_push_rule_attrs.py [hunk 14]
```diff
@@ -0,0 +1,448 @@
...
+
+        # check rule enabled
+        request, channel = self.make_request(
+            "GET", "/pushrules/global/override/best.friend/enabled", access_token=token
+        )
+        self.render(request)
+        self.assertEqual(channel.code, 200)
+        self.assertEqual(channel.json_body["enabled"], True)
+
+    def test_enabled_404_when_get_inexistent(self):
```
Comment (richvdh) [inline tests/rest/client/v1/test_push_rule_attrs.py:183]: NON_EXISTENT

File: synapse/storage/data_stores/main/push_rule.py (hunk 2 above)
Comment (reivilibre) [reply synapse/storage/data_stores/main/push_rule.py:16]: I think one of the lint tools (isort?) ate that :/, sorry

File: synapse/rest/client/v1/push_rule.py (hunk 4 above)
Comment (reivilibre) [reply synapse/rest/client/v1/push_rule.py:176]: Aha, OK, I blindly copied `%r` from somewhere else. For my own reference, `%r` does `repr(…)`.

File: synapse/storage/data_stores/main/push_rule.py (hunk 8 above)
Comment (reivilibre) [reply synapse/storage/data_stores/main/push_rule.py:743]: Thanks for the insight :)

File: synapse/storage/data_stores/main/schema/delta/59/pushrules_enabled_delete_obsolete.sql (hunk 13 above)
Comment (reivilibre) [reply synapse/storage/data_stores/main/schema/delta/59/pushrules_enabled_delete_obsolete.sql:23]: Oui, I didn't think of that, thanks

File: tests/rest/client/v1/test_push_rule_attrs.py (hunk 14 above)
Comment (reivilibre) [reply tests/rest/client/v1/test_push_rule_attrs.py:183]: :^)

File: synapse/storage/data_stores/main/push_rule.py (hunk 5 above)
Comment (reivilibre) [reply synapse/storage/data_stores/main/push_rule.py:688]: Objective was to make it have a code of `NOT_FOUND` rather than `UNKNOWN`. Comment worthwhile?

File: synapse/rest/client/v1/push_rule.py (hunk 3 above)
Comment (reivilibre) [reply synapse/rest/client/v1/push_rule.py:175]: Ta! :)

File: synapse/storage/data_stores/main/push_rule.py (hunk 7 above)
Comment (richvdh) [reply synapse/storage/data_stores/main/push_rule.py:683]: bump

File: synapse/storage/data_stores/main/push_rule.py (hunk 5 above)
Comment (richvdh) [reply synapse/storage/data_stores/main/push_rule.py:688]: gah, I see. Well, can you use `NotFoundError`, and document it in the docstring for `set_push_rule_enabled` ?

File: synapse/storage/data_stores/main/push_rule.py [hunk 15]
```diff
@@ -656,12 +662,31 @@ def set_push_rule_enabled(self, user_id, rule_id, enabled):
...
         new_id = self._push_rules_enable_id_gen.get_next()
+
+        if not is_default_rule:
+            try:
+                # first check it exists
+                self.db.simple_select_one_onecol_txn(
+                    txn, "push_rules", {"user_name": user_id, "rule_id": rule_id}, "id"
+                )
+            except StoreError as serr:
+                if serr.code == 404:
```
Comment (richvdh) [inline synapse/storage/data_stores/main/push_rule.py:687]: looks like you're swallowing other errors here

File: synapse/storage/data_stores/main/push_rule.py [hunk 16]
```diff
@@ -702,12 +727,20 @@ def set_push_rule_actions_txn(txn, stream_id, event_stream_ordering):
...
+                        txn,
+                        "push_rules",
+                        {"user_name": user_id, "rule_id": rule_id},
+                        {"actions": actions_json},
+                    )
+                except StoreError as serr:
+                    if serr.code == 404:
+                        raise StoreError(
+                            404, "Push rule does not exist", Codes.NOT_FOUND
+                        )
```
Comment (richvdh) [inline synapse/storage/data_stores/main/push_rule.py:741]: again: NotFoundError, docstring.

**Comment by reivilibre** [comment]
So the write skew stuff is an interesting problem.

I posed a question: will this execution flow cause us a dangling enabled row on REPEATABLE READ isolation level as used in Synapse?

```
1: BEGIN -- set_enabled
2: BEGIN -- delete_push_rule
1: SELECT push_rule WHERE id=a -- found!
2: DELETE push_rule WHERE id=a
2: DELETE push_rule_enabled WHERE id=a -- (0 deleted)
1: INSERT INTO push_rule_enabled (id=a, ...)
1: COMMIT
2: COMMIT
```


To set up an experiment, I got out psql and tried:

```sql
CREATE TABLE push_rules1(id TEXT PRIMARY KEY);
CREATE TABLE push_rules_enabled1(id TEXT PRIMARY KEY, enabled BOOL);
INSERT INTO push_rules1 VALUES ('a');
```

then I got two psqls up and did this test:

```sql
1 $ BEGIN ISOLATION LEVEL REPEATABLE READ;
2 $ BEGIN ISOLATION LEVEL REPEATABLE READ;
1 $ SELECT * FROM push_rules1 WHERE id='a';
 id 
----
 a
(1 row)
2 $ DELETE FROM push_rules1 WHERE id='a';
DELETE 1
2 $ DELETE FROM push_rules_enabled1 WHERE id='a';
DELETE 0
1 $ INSERT INTO push_rules_enabled1 VALUES ('a', TRUE);
INSERT 0 1
1 $ COMMIT;
COMMIT
2 $ COMMIT;
COMMIT

$ SELECT * FROM push_rules1;
 id 
----
(0 rows)

$ SELECT * FROM push_rules_enabled1;
 id | enabled 
----+---------
 a  | t
(1 row)

oups!
```

OK, so no real surprise, we get a serialisation anomaly here (a write skew, I believe)

now with `SELECT FOR KEY SHARE`, which will lock the row such that it cannot be deleted until we unlock it.

```sql
1 $ BEGIN ISOLATION LEVEL REPEATABLE READ;
2 $ BEGIN ISOLATION LEVEL REPEATABLE READ;
1 $ SELECT * FROM push_rules1 WHERE id='a' FOR KEY SHARE;
 id 
----
 a
(1 row)
2 $ DELETE FROM push_rules1 WHERE id='a';
<blocks>
-- 2 is blocked so can't run other query yet.
1 $ INSERT INTO push_rules_enabled1 VALUES ('a', TRUE);
INSERT 0 1
1 $ COMMIT;
-- now 2 unblocks
2 $ DELETE FROM push_rules_enabled1 WHERE id='a';
DELETE 0 — urr
2 $ COMMIT;

-- and then:

$ SELECT * FROM push_rules1;
 id 
----
(0 rows)

$ SELECT * FROM push_rules_enabled1;
 id | enabled 
----+---------
 a  | t
(1 row)
```

So, grumble grumble, `FOR KEY SHARE` isn't a silver bullet!

I can't think of a way to re-order these to make it race-safe…

I believe you'd have to go SERIALISABLE instead of REPEATABLE READ if you cared about no dangling enabled rows… Is there something I'm missing?

**Review by richvdh — APPROVED** [review]
lgtm, thanks!

sytests would have been nice, but hohum.
