### PR TITLE
Fix a bug when a room alias is given to the admin join endpoint

### LINKED ISSUE #9505: ValueError: Attempted to iterate a RoomID
### Description
Hi,
I was using the join admin route, but it seems to not work anymore maybe since i've updated synapse. This issue happen only when i'm using alias but not an room_id
Here is the log :

```
2021-02-26 14:01:23,554 - synapse.http.server - 94 - ERROR - POST-320 - Failed handle request via 'JoinRoomAliasServlet': <XForwardedForRequest at 0x7feef12ec358 method='POST' uri='/_synapse/admin/v1/join/%23test%3Aexemple.test.com' clientproto='HTTP/1.1' site='8008'>
Traceback (most recent call last):
  File "/opt/synapse2/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/synapse2/env/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/synapse2/env/lib/python3.6/site-packages/synapse/storage/databases/main/event_federation.py", line 634, in get_latest_event_ids_in_room
    desc="get_latest_event_ids_in_room",
  File "/opt/synapse2/env/lib/python3.6/site-packages/synapse/storage/database.py", line 1453, in simple_select_onecol
    db_autocommit=True,
  File "/opt/synapse2/env/lib/python3.6/site-packages/synapse/storage/database.py", line 676, in runInteraction
    **kwargs,
  File "/opt/synapse2/env/lib/python3.6/site-packages/synapse/storage/database.py", line 752, in runWithConnection
    self._db_pool.runWithConnection(inner_func, *args, **kwargs)
  File "/opt/synapse2/env/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/opt/synapse2/env/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/opt/synapse2/env/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/opt/synapse2/env/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/opt/synapse2/env/lib/python3.6/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/opt/synapse2/env/lib/python3.6/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/opt/synapse2/env/lib/python3.6/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/opt/synapse2/env/lib/python3.6/site-packages/synapse/storage/database.py", line 746, in inner_func
    return func(db_conn, *args, **kwargs)
  File "/opt/synapse2/env/lib/python3.6/site-packages/synapse/storage/database.py", line 540, in new_transaction
    r = func(cursor, *args, **kwargs)
  File "/opt/synapse2/env/lib/python3.6/site-packages/synapse/storage/database.py", line 1422, in simple_select_onecol_txn
    txn.execute(sql, list(keyvalues.values()))
  File "/opt/synapse2/env/lib/python3.6/site-packages/synapse/storage/database.py", line 295, in execute
    self._do_execute(self.txn.execute, sql, *args)
  File "/opt/synapse2/env/lib/python3.6/site-packages/synapse/storage/database.py", line 321, in _do_execute
    return func(sql, *args)
  File "/opt/synapse2/env/lib/python3.6/site-packages/psycopg2/extensions.py", line 121, in getquoted
    pobjs = [adapt(o) for o in self._seq]
  File "/opt/synapse2/env/lib/python3.6/site-packages/synapse/types.py", line 220, in __iter__
    raise ValueError("Attempted to iterate a %s" % (type(self).__name__,))
ValueError: Attempted to iterate a RoomID
```

I tried to reinstall a new server with a new database, got the same issue.
I installed a new synapse server in 1.25.0, it was not working too

I just installed a new server in 1.23.0 and it works !

### Version information

- **Version**:
Synapse 1.28.0

- **Install method**:
Installed via pip

### PR DESCRIPTION
**Pull request by clokep**
Fixes #9505 and attempts to improve the code a bit while we're there.

Each commit should be reviewable individually.

### CODE REVIEW

File: changelog.d/9506.bugfix [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix a bug introduced in v1.25.0: `ValueError: Attempted to iterate a RoomID` when attempting to use `/_synapse/admin/join/` with a room alias.
```
Comment (erikjohnston) [inline changelog.d/9506.bugfix:1]:
```suggestion
Fix a bug introduced in v1.25.0 where `/_synapse/admin/join/` would fail when given a room alias.
```

As that's probably clearer what the effect is?

**Review by erikjohnston — APPROVED** [review]
