### PR TITLE
Fix support for SQLite 3.7.

### LINKED ISSUE #6246: 'sqlite3.OperationalError: near "WHERE"' on sqlite 3.7
Hi, I have problem, on first run:

```
(env) [root@chat synapse]# synctl start
Starting ...
This server is configured to use 'matrix.org' as its trusted key server via the
'trusted_key_servers' config option. 'matrix.org' is a good choice for a key
server since it is long-lived, stable and trusted. However, some admins may
wish to use another server for this purpose.

To suppress this warning and continue using 'matrix.org', admins should set
'suppress_key_server_warning' to 'true' in homeserver.yaml.
--------------------------------------------------------------------------------
2019-10-24 13:40:10,455 - twisted - 171 - INFO - None - Redirected stdout/stderr to logs
2019-10-24 13:40:10,455 - root - 236 - WARNING - None - ***** STARTING SERVER *****
2019-10-24 13:40:10,455 - root - 237 - WARNING - None - Server /var/www/synapse/env/lib/python3.6/site-packages/synapse/app/homeserver.py version 1.4.1
2019-10-24 13:40:10,456 - root - 238 - INFO - None - Server hostname: matrix.omnichat.tech
2019-10-24 13:40:10,457 - synapse.app.homeserver - 359 - INFO - None - Preparing database: sqlite3...
2019-10-24 13:40:16,312 - synapse.storage.prepare_database - 249 - INFO - None - Upgrading schema to v55
2019-10-24 13:40:16,313 - synapse.storage.prepare_database - 287 - INFO - None - Applying schema 55/access_token_expiry.sql
2019-10-24 13:40:16,314 - synapse.storage.prepare_database - 287 - INFO - None - Applying schema 55/track_threepid_validations.sql
2019-10-24 13:40:16,316 - synapse.storage.prepare_database - 287 - INFO - None - Applying schema 55/users_alter_deactivated.sql
2019-10-24 13:40:16,316 - synapse.storage.prepare_database - 249 - INFO - None - Upgrading schema to v56
2019-10-24 13:40:16,317 - synapse.storage.prepare_database - 287 - INFO - None - Applying schema 56/add_spans_to_device_lists.sql
2019-10-24 13:40:16,318 - synapse.storage.prepare_database - 287 - INFO - None - Applying schema 56/current_state_events_membership.sql
2019-10-24 13:40:16,318 - synapse.storage.prepare_database - 287 - INFO - None - Applying schema 56/current_state_events_membership_mk2.sql
2019-10-24 13:40:16,319 - synapse.storage.prepare_database - 287 - INFO - None - Applying schema 56/destinations_failure_ts.sql
2019-10-24 13:40:16,320 - synapse.storage.prepare_database - 287 - INFO - None - Applying schema 56/devices_last_seen.sql
2019-10-24 13:40:16,322 - synapse.storage.prepare_database - 287 - INFO - None - Applying schema 56/fix_room_keys_index.sql
2019-10-24 13:40:16,323 - synapse.storage.prepare_database - 287 - INFO - None - Applying schema 56/redaction_censor.sql
2019-10-24 13:40:16,324 - twisted - 171 - ERROR -  - Traceback (most recent call last):
2019-10-24 13:40:16,325 - twisted - 171 - ERROR -  -   File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
2019-10-24 13:40:16,326 - twisted - 171 - ERROR -  -     "__main__", mod_spec)
2019-10-24 13:40:16,326 - twisted - 171 - ERROR -  -   File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
2019-10-24 13:40:16,326 - twisted - 171 - ERROR -  -     exec(code, run_globals)
2019-10-24 13:40:16,326 - twisted - 171 - ERROR -  -   File "/var/www/synapse/env/lib/python3.6/site-packages/synapse/app/homeserver.py", line 659, in <module>
2019-10-24 13:40:16,327 - twisted - 171 - ERROR -  -     main()
2019-10-24 13:40:16,327 - twisted - 171 - ERROR -  -   File "/var/www/synapse/env/lib/python3.6/site-packages/synapse/app/homeserver.py", line 654, in main
2019-10-24 13:40:16,328 - twisted - 171 - ERROR -  -     hs = setup(sys.argv[1:])
2019-10-24 13:40:16,328 - twisted - 171 - ERROR -  -   File "/var/www/synapse/env/lib/python3.6/site-packages/synapse/app/homeserver.py", line 363, in setup
2019-10-24 13:40:16,329 - twisted - 171 - ERROR -  -     prepare_database(db_conn, database_engine, config=config)
2019-10-24 13:40:16,329 - twisted - 171 - ERROR -  -   File "/var/www/synapse/env/lib/python3.6/site-packages/synapse/storage/prepare_database.py", line 74, in prepare_database
2019-10-24 13:40:16,329 - twisted - 171 - ERROR -  -     _setup_new_database(cur, database_engine)
2019-10-24 13:40:16,330 - twisted - 171 - ERROR -  -   File "/var/www/synapse/env/lib/python3.6/site-packages/synapse/storage/prepare_database.py", line 171, in _setup_new_database
2019-10-24 13:40:16,330 - twisted - 171 - ERROR -  -     is_empty=True,
2019-10-24 13:40:16,330 - twisted - 171 - ERROR -  -   File "/var/www/synapse/env/lib/python3.6/site-packages/synapse/storage/prepare_database.py", line 288, in _upgrade_existing_database
2019-10-24 13:40:16,331 - twisted - 171 - ERROR -  -     executescript(cur, absolute_path)
2019-10-24 13:40:16,331 - twisted - 171 - ERROR -  -   File "/var/www/synapse/env/lib/python3.6/site-packages/synapse/storage/prepare_database.py", line 427, in executescript
2019-10-24 13:40:16,332 - twisted - 171 - ERROR -  -     txn.execute(statement)
2019-10-24 13:40:16,332 - twisted - 171 - ERROR -  - sqlite3.OperationalError: near "WHERE": syntax error
```

### PR DESCRIPTION
**Pull request by erikjohnston**
Partial indices support was added in 3.8.0, so we need to use the background updates that handles this correctly.

Fixes #6246. Broke in #5934.

### CODE REVIEW

File: synapse/storage/data_stores/main/schema/delta/56/redaction_censor.sql [hunk 1]
```diff
@@ -14,4 +14,6 @@
  */
 
 ALTER TABLE redactions ADD COLUMN have_censored BOOL NOT NULL DEFAULT false;
-CREATE INDEX redactions_have_censored ON redactions(event_id) WHERE not have_censored;
+
+INSERT INTO background_updates (update_name, progress_json) VALUES
```
Comment (richvdh) [inline synapse/storage/data_stores/main/schema/delta/56/redaction_censor.sql]: I'm a bit surprised we need this at all tbh

File: synapse/storage/data_stores/main/schema/delta/56/redaction_censor2.sql [hunk 2]
```diff
@@ -14,7 +14,9 @@
  */
 
 ALTER TABLE redactions ADD COLUMN received_ts BIGINT;
-CREATE INDEX redactions_have_censored_ts ON redactions(received_ts) WHERE not have_censored;
 
 INSERT INTO background_updates (update_name, progress_json) VALUES
   ('redactions_received_ts', '{}');
+
+INSERT INTO background_updates (update_name, progress_json) VALUES
```
Comment (richvdh) [inline synapse/storage/data_stores/main/schema/delta/56/redaction_censor2.sql]: can we stop the redaction job starting (and pinning a db connection) until this has completed?

File: synapse/storage/data_stores/main/schema/delta/56/redaction_censor.sql (hunk 1 above)
Comment (erikjohnston) [reply synapse/storage/data_stores/main/schema/delta/56/redaction_censor.sql]: As in, the index?

Comment (richvdh) [reply synapse/storage/data_stores/main/schema/delta/56/redaction_censor.sql]: ja

File: synapse/storage/data_stores/main/events.py [hunk 3]
```diff
@@ -1053,6 +1053,13 @@ def _censor_redactions(self):
         if self.hs.config.redaction_retention_period is None:
             return
 
+        if self.db.updates.has_completed_background_update(
```
Comment (richvdh) [inline synapse/storage/data_stores/main/events.py]: async function is async

Comment (erikjohnston) [reply synapse/storage/data_stores/main/events.py]: Yup, so I noticed this, stuck a yield in, and then started questioning yielding on coroutine and :sob: :sob: :sob:

Comment (erikjohnston) [reply synapse/storage/data_stores/main/events.py]: Also, there should be a `not` there.

**Comment by richvdh** [comment]
wdyt about putting this in synapse 1.7.0 ?

**Comment by erikjohnston** [comment]
> wdyt about putting this in synapse 1.7.0 ?

Potentially, I'd certainly want it to go out through an RC first though.
