### PR TITLE
Fix race calling `/members?at=`

### LINKED ISSUE #14814: members API returns `M_NOT_FOUND: MatrixError: [404] Can't find event for token`
### Description

See https://github.com/vector-im/element-web/issues/24179.

The user is creating a new DM room.

Element Web creates the room, waits for a sync, then calls the members API with the latest sync token:

```
https://matrix-client.matrix.org/_matrix/client/r0/rooms/!lFfrlZXUrMAOXpzuxp%3Amatrix.org/members?not_membership=leave&at=m3595246325%7E2.3595246467%7E3.3595246468%7E36.3595246466_757284974_52668403_1826042582_1854740460_3893944_721765062_6284542923_0
```

### Steps to reproduce

Since we're using a sync token given to us by Synapse from a sync that contains the new room's events, we would expect it to point to a valid event in the room.

### Homeserver

matrix.org

### Synapse Version

1.75.0rc1 (b=matrix-org-hotfixes,04aa6a9707)

But note that this was reported on 2023-01-06T11:49 UTC

### Installation Method

I don't know

### Database

PostgreSQL

### Workers

Multiple workers

### Platform

.

### Configuration

.

### Relevant log output

```shell
Element web logs: https://github.com/matrix-org/element-web-rageshakes/issues/18940
```

### Anything else that would be useful to know?

@richvdh is already investigating.

### PR DESCRIPTION
**Pull request by erikjohnston**
Fixes #14814

### CODE REVIEW

File: changelog.d/14817.bugfix [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix race where calling `/members` or `/state` with an `at` parameter could fail for newly created rooms, when using multiple workers.
```
Comment (DMRobertson) [inline changelog.d/14817.bugfix:1]: Is it just newly-created rooms that are vulnerable to this race? E.g. are there other consumers of `get_last_event_in_room_before_stream_ordering`?

File: synapse/storage/databases/main/stream.py [hunk 2]
```diff
@@ -801,13 +801,66 @@ async def get_last_event_in_room_before_stream_ordering(
             before this stream ordering.
         """
 
-        last_row = await self.get_room_event_before_stream_ordering(
```
Comment (DMRobertson) [inline synapse/storage/databases/main/stream.py:804]: Is `get_room_event_before_stream_ordering` just wrong? Should we be auditing its other call sites?

File: changelog.d/14817.bugfix (hunk 1 above)
Comment (erikjohnston) [reply changelog.d/14817.bugfix:1]: Hmm, it can also be a bit weird if it races with any state change, as it may return the state *before* the state change. And I guess joins would also do something weird here.

Will update.

File: synapse/storage/databases/main/stream.py [hunk 3]
```diff
@@ -801,13 +801,66 @@ async def get_last_event_in_room_before_stream_ordering(
...
+                    SELECT instance_name, stream_ordering, topological_ordering, event_id
+                    FROM events
+                    LEFT JOIN rejections USING (event_id)
+                    WHERE room_id = ?
+                        AND stream_ordering <= ?
+                        AND NOT outlier
+                        AND rejections.event_id IS NULL
+                    ORDER BY stream_ordering DESC
+                    LIMIT 1
+                ) AS b
```
Comment (DMRobertson) [inline synapse/storage/databases/main/stream.py:835]: The query's of the form
```
SELECT * FROM ( SELECT XXXXXXXX ) as a
UNION
SELECT * FROM ( SELECT YYYYYYYY ) as b
```

Is there any reason for spelling it this way rather than `SELECT XXXXXXXX UNION SELECT YYYYYYYY`?

**Review by DMRobertson — COMMENTED** [review]
I think this seems sane (though it took me some time to understand wtf was going on).

The only thing I'm worried about is that `get_room_event_before_stream_ordering` might be a footgun today?

File: synapse/storage/databases/main/stream.py (hunk 3 above)
Comment (erikjohnston) [reply synapse/storage/databases/main/stream.py:835]: sqlite :sob:

**Review by DMRobertson — APPROVED** [review]
