### PR TITLE
Load SSO rest API for redirect only if SSO is enabled

### LINKED ISSUE #15402: SSO rest API for redirect is loaded if no SSO is configured
### Description

Rest api is loaded and can be called if no SSO is configured.

API returns an error "Homeserver not configured for SSO." But I can not see why the server needs to be run this api.

### Steps to reproduce

- setup a new homeserver
- request /_matrix/client/r0/login/sso/redirect?redirectUrl=www.example.org

### Homeserver

another

### Synapse Version

1.78.0

### Installation Method

Docker (matrixdotorg/synapse)

### Database

PostgreSQL

### Workers

Single process

### Platform

K8s

### Configuration

only password login

### Relevant log output

```shell
None
```

### Anything else that would be useful to know?

Probably there could be a check here for SSO capabilities:

https://github.com/matrix-org/synapse/blob/98fd558382226b347d78e5f6e6782c6e74c25e69/synapse/rest/client/login.py#L675

Similar to:
https://github.com/matrix-org/synapse/blob/98fd558382226b347d78e5f6e6782c6e74c25e69/synapse/rest/client/login.py#L148

### PR DESCRIPTION
**Pull request by dklimpel**
Closes #15402 

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

Signed-off-by: Dirk Klimpel 5740567+dklimpel@users.noreply.github.com

### CODE REVIEW

File: changelog.d/15421.misc [hunk 1]
```diff
@@ -0,0 +1 @@
+Load SSO rest API for redirect only if SSO is enabled.
```
Comment (clokep) [inline changelog.d/15421.misc:1]:
```suggestion
Only load the SSO redirect servlet if SSO is enabled.
```

**Review by clokep — APPROVED** [review]
LGTM
